### PR TITLE
use stabilized clamp()

### PR DESCRIPTION
**Pull request by MaxVerevkin**
This requires rust 1.50.0

### CODE REVIEW

**Comment by ammgws** [comment]
Might sit on this one for a bit

**Comment by MaxVerevkin** [comment]
By the way, is there a way to request github actions to rerun?

**Comment by ammgws** [comment]
image
You don't have that button near the top right?

**Comment by MaxVerevkin** [comment]
That's what I have

image

**Comment by ammgws** [comment]
Hmm not sure then. Will have to look into it. I'll manually trigger it for you now.

**Comment by MaxVerevkin** [comment]
I guess only collaborators have is but this weird.

**Comment by MaxVerevkin** [comment]
I did some research using `grep` and it turns out `GraphWidget` is not used at all.

Also remove `num-traits` dependency.

**Comment by MaxVerevkin** [comment]
It compiles!

**Comment by ammgws** [comment]
Also replace the clamp_root_scaling function?

**Comment by MaxVerevkin** [comment]
> Also replace the clamp_root_scaling function?

This?
```rust
/// Clamp scale root to a safe range. Useful values are 1.0 to 3.0.
fn clamp_root_scaling(root_scaling: f64) -> f64 {
    if 0.1 < root_scaling && root_scaling < 10.0 {
        root_scaling
    } else {
        1.0
    }
}
```
I'm not sure how and why.

**Comment by ammgws** [comment]
Don't worry about it!

Anyway I'll go ahead and merge this since the next release probably won't be out for a while and we do state that we require recent versions of rustc in the readme.

**Pull request merged**
