### PR TITLE
implement merge_with_next option

### LINKED ISSUE #1539: How to disable alternating tint for a specific block?
@GladOSkar Was this even possible in the first implementation you submitted in https://github.com/greshake/i3status-rust/pull/927?

Basically just want to disable tints between two adjacent blocks so that they visually appear as one, but the tint applies anyway even with the below config:

```toml
[[block]]
block = "bluetooth"
[block.theme_overrides]
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[[block]]
block = "battery"
[block.theme_overrides]
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
```

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Fixes #1539

### Example config

```toml
[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume |}"
device_kind = "sink"
merge_with_next = true # <===

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume |}"
device_kind = "source"
[block.theme_overrides]
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
```

in `i3bar-river`:

image

### TODO

- [ ] Test with `swaybar` and `i3bar`
- [ ] Test with different separators.
- [ ] Docs

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
@ammgws Do you use this option? I think it was pretty much broken for non-native separators (native separators are rendered _after_ the block, non-native separators render _before_ the block). I think I fixed it in ca6f01c.

**Comment by ammgws** [comment]
I am using it to with combine `bluetooth` and `upower` since the former doesn't show battery information for my device, but haven't had time to play around with separators yet so left it undocumented.

**Comment by ammgws** [comment]
Merging bluetooth and battery blocks together. Sometimes end up like this, weird...

image

**Comment by MaxVerevkin** [comment]
f34c70f should fix this

**Pull request merged**
