### PR TITLE
generate manpage in xtask, add manpage to gitignore

### LINKED ISSUE #1422: Add manpage generation to GitHub actions?
Keep forgetting to update them since it's manual process ATM

### LINKED ISSUE #1794: man/_preface.1 is outdated

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Closes #1422
Closes #1794
Closes #1803

This is an adaptation of https://github.com/hrkfdn/ncspot/pull/1059.

## TODO

- [x] `clap_mangen` integration
- [x] Document the packaging process (run `cargo xtask generate-manpage` to generate `man/i3status-rs.1`)

### CODE REVIEW

**Comment by bim9262** [comment]
This looks like a really cool approach!

**Review by ammgws — COMMENTED** [review]
It would be better if we honored XDG dirs in the install script the same way we do inside the application itself, since right now it's hardcoded to ~/.local/xxx

**Comment by MaxVerevkin** [comment]
> It would be better if we honored XDG dirs in the install script the same way we do inside the application itself, since right now it's hardcoded to ~/.local/xxx

Done in d1e6c93

**Comment by bim9262** [comment]
`$XDG_DATA_HOME` may not be set on all systems, I think we need to have a fallback like `${XDG_DATA_HOME:-$HOME/.local/share}`

**Comment by MaxVerevkin** [comment]
@bim9262 I'm pretty sure that's what I did ;)

**Comment by bim9262** [comment]
Sorry, missed the top line!

**Pull request merged**
