### PR TITLE
microphone support

### PR DESCRIPTION
**Pull request by remi-dupre**
This is (apparently) the third attempt for https://github.com/greshake/i3status-rust/pull/352.

Note that this is a duplicate of https://github.com/greshake/i3status-rust/pull/371, which I didn't use since there was quite a lot of conflicts and some changes had to be done anyway. I took a similar approach so this may not be an issue.

Should I update the manpages? Running `generate.sh` seems to introduce ~1600 changes to the file right now :(

*NOTE*: The sound module is quite big, should we consider an attempt of splitting it in separate modules (eg: alsa, pulsoaudio, and generic module)? I could attempt to do this in this PR if you think this may be relevant.

### CODE REVIEW

**Comment by ammgws** [comment]
I haven't had a chance to look at the code yet, but does this address the comments from the previous PR about duplicating the client?

**Comment by remi-dupre** [comment]
> I haven't had a chance to look at the code yet, but does this address the comments from the previous PR about duplicating the client?

Yes, it's using a single client to take track of states for both sources and sinks.

**Comment by ammgws** [comment]
Can you update the docs too?

**Comment by remi-dupre** [comment]
> Can you update the docs too?

Done!

Also, it just made me realize that I totally forgot to support ALSA in this PR. In https://github.com/greshake/i3status-rust/pull/371 it seems pretty short and straightforward, however this part seems to have slightly changed since. I currently don't have any setup to test/experiment with ALSA but I'll try to dive into it :)

**Comment by ammgws** [comment]
Pretty sure ALSA supports mic already - all you have to do is set `name = "Capture"` or whatever your mic shows up as in the output of `amixer`

**Comment by remi-dupre** [comment]
Oh indeed, you're right!

**Comment by ammgws** [comment]
Can you fix the blocks.md conflict?

> the sound module is quite big, should we consider an attempt of splitting it in separate modules (eg: alsa, pulsoaudio, and generic module)? I could attempt to do this in this PR if you think this may be relevant.

We can leave this for another PR, though I think some other blocks are similarly large.

**Comment by remi-dupre** [comment]
> Can you fix the blocks.md conflict?

:heavy_check_mark:
It seems that some encoding issue appeared, I'm not sure how I introduced that

> We can leave this for another PR, though I think some other blocks are similarly large.

Do you think it would be relevant to spend some time on it? I'd love to spend some time on this project and sometime (I found it a few days ago, it's awesome, thanks for your work btw!). Plus, I'm kind of a tidying nerd ^^'

Updating the manpages still generates a huge diff, am I missing something? Maybe this is just a pandoc version issue? (`pandoc -v`: 2.9.2.1)

**Comment by ammgws** [comment]
The encoding issue was due to another PR. 

I think it would be better to spend time on end user features such as new blocks, but if you're interested in tidying up then it can't hurt to give it a go and see what we can come up with.

I'm not sure about the manpages as they were added by atheriel, perhaps you could check some past PRs and see if it was the same diff volume for them?

**Comment by remi-dupre** [comment]
> I'm not sure about the manpages as they were added by atheriel, perhaps you could check some past PRs and see if it was the same diff volume for them?

I think I was overthinking, it was just not udpated for [some time](https://github.com/greshake/i3status-rust/commits/master/man/i3status-rs.1) and git seems to have a hard time dealing with this big update, many lines counted in the diff actually didn't change.

**Comment by ammgws** [comment]
Thanks!

**Pull request merged**
