### PR TITLE
Change to State::Good in battery charging mode.

### PR DESCRIPTION
**Pull request by droslean**
Change battery state to "Good" in charging mode. That changes also the highlight green when the battery is charging.

### CODE REVIEW

**Comment by atheriel** [comment]
Note that this has merge conflicts that must be resolved. I don't have strong feelings about whether the battery is always "good" when it's plugged in; perhaps you do, @greshake?

**Comment by droslean** [comment]
@atheriel Conflicts have been resolved.  Please check.

**Comment by droslean** [comment]
@atheriel @greshake  Any news?

**Comment by atheriel** [comment]
LGTM :+1:

**Pull request merged**
