### PR TITLE
Add option to show marks instead of title

### PR DESCRIPTION
**Pull request by ammgws**
This can be merged once tmerr/i3ipc-rs/pull/51 has been implemented.

Solves #486

### CODE REVIEW

**Comment by travankor** [comment]
@ammgws 
Sorry for not getting to this earlier, but this works well so far.

Something to consider: I only use 1 mark per window, but sway lets you have several marks per window if you do `swaymsg mark [mark1]` and `swaymsg -- mark --add [mark2]` . So maybe multiple marks should get enclosed in brackets?

Also some interesting info from the man page:
```
show_marks yes|no
           If show_marks is yes, marks will be displayed in the window
           borders.  Any mark that starts with an underscore will not be drawn
           even if show_marks is yes. The default is yes.
```
I don't think that i3status-rust should follow this rule. I think there would be too many edge cases from this and marks are not shown by default so not much benefit with dealing with this.

**Comment by ammgws** [comment]
I can look into the multiple marks thing and an option to hide the underscored ones. If the i3ipc crate is updated before that then we can just merge this simple implementation now and add those features later.

**Comment by ammgws** [comment]
@travankor this is now implemented using the swayipc-rs crate. It works fine for me, please let me know if there are any issues.

**Comment by travankor** [comment]
@ammgws seems like it works well but the issues raised [here](https://github.com/greshake/i3status-rust/pull/532#issuecomment-581854186) remain.

Also the binary size has gone up a significant bit since the last release -- from 6M to 11M.

**Comment by ammgws** [comment]
So with one mark set, e.g. "abc", the bar should display: "abc"

And with multiple marks set, e.g. "abc" and "def", the bar should display: "[abc] [def]"

?

If the binary size is a problem then I will have to look into later. Perhaps enabling LTO could help. Do you mean last release as in the last tagged version vs git master?

**Comment by travankor** [comment]
>So with one mark set, e.g. "abc", the bar should display: "abc"
And with multiple marks set, e.g. "abc" and "def", the bar should display: "[abc] [def]"

1)Currently multiple marks get concatenated, and it looks like one giant mark. `swaymsg -- mark --add anothermark' for example.

2)Marks that begin with underscores are considered hidden.

> Do you mean last release as in the last tagged version vs git master?

Yes. It's not a problem for me personally; I just noticed this and reported it.

**Comment by ammgws** [comment]
> Currently multiple marks get concatenated, and it looks like one giant mark. swaymsg -- mark --add anothermark for example.

I don't use marks so I wasn't sure what it looked like in the first place. This is what one mark and two marks looks like for me: 
image

I was thinking about making i3status-rust show multiple marks with brackets around each one like sway does, but looks like sway does it for the singular case as well so I guess I will change that too.

**Comment by ammgws** [comment]
> Also the binary size has gone up a significant bit since the last release -- from 6M to 11M.

FYI enabling link time optimizations brings it down to 8.6MB

**Pull request merged**
