### PR TITLE
memory: Count ZFS arc cache to cache to exclude from used memory

### LINKED ISSUE #1216: Memory and htop
There is somtheing I dont get

i3status-rs tells me I have 50GB of ram used, htop tells me 18GB

20210507_1441_1479x1083_1620391276

```
 block = "memory"                                                                
 format_mem = "tot:{mem_total} free:{mem_free} used:{mem_used} avail:{mem_avail} cached:{cached}"
```

### PR DESCRIPTION
**Pull request by GladOSkar**
Resolves #1216

Not sure what the current policy on shelling out is, but this should be fast enough and is way shorter than anything i could come up with using native code.

Feedback welcome :)

### CODE REVIEW

**Comment by ammgws** [comment]
Something like this should work:

```rust
    let re = Regex::new(r"size\s+\d+\s+(\d+)").unwrap(); // Valid regex is safe to unwrap.
    let mut raw = String::new();
    File::open("/proc/spl/kstat/zfs/arcstats").unwrap().read_to_string(&mut raw);
    let cap = re.captures(&raw).unwrap();
    eprintln!("{}", cap[1].to_string());
```

Or at least it worked when I tested with a file like this (randomly grabbed from the net since I don't have ZFS):

```
4 1 0x01 84 4032 43757119584 392054268420115
name                            type data
hits                            4    28057644
misses                          4    13975282
demand_data_hits                4    19632274
demand_data_misses              4    571809
demand_metadata_hits            4    6333604
demand_metadata_misses          4    289110
prefetch_data_hits              4    1903379
prefetch_data_misses            4    12884520
prefetch_metadata_hits          4    188387
prefetch_metadata_misses        4    229843
mru_hits                        4    15390332
mru_ghost_hits                  4    1088944
mfu_hits                        4    10586761
mfu_ghost_hits                  4    169152
deleted                         4    35432344
recycle_miss                    4    701686
mutex_miss                      4    35304
evict_skip                      4    60416647
evict_l2_cached                 4    0
evict_l2_eligible               4    3022396862976
evict_l2_ineligible             4    1602907651584
hash_elements                   4    212777
hash_elements_max               4    256438
hash_collisions                 4    17163377
hash_chains                     4    51485
hash_chain_max                  4    10
p                               4    1527347963
c                               4    7572030912
c_min                           4    1038188800
c_max                           4    1073741824
size                            4    7572198224
hdr_size                        4    66873056
data_size                       4    7496095744
other_size                      4    9229424
anon_size                       4    169150464
anon_evict_data                 4    0
anon_evict_metadata             4    0
mru_size                        4    1358216192
mru_evict_data                  4    1352400896
mru_evict_metadata              4    508928
mru_ghost_size                  4    6305992192
mru_ghost_evict_data            4    4919159808
mru_ghost_evict_metadata        4    1386832384
mfu_size                        4    5968729088
mfu_evict_data                  4    5627991552
mfu_evict_metadata              4    336846336
mfu_ghost_size                  4    1330455552
mfu_ghost_evict_data            4    1287782400
mfu_ghost_evict_metadata        4    42673152
l2_hits                         4    0
l2_misses                       4    0
l2_feeds                        4    0
l2_rw_clash                     4    0
l2_read_bytes                   4    0
l2_write_bytes                  4    0
l2_writes_sent                  4    0
l2_writes_done                  4    0
l2_writes_error                 4    0
l2_writes_hdr_miss              4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_free_on_write                4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    0
l2_asize                        4    0
l2_hdr_size                     4    0
l2_compress_successes           4    0
l2_compress_zeros               4    0
l2_compress_failures            4    0
memory_throttle_count           4    0
duplicate_buffers               4    0
duplicate_buffers_size          4    0
duplicate_reads                 4    0
memory_direct_count             4    66583
memory_indirect_count           4    7657293
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    0
arc_meta_used                   4    427048272
arc_meta_limit                  4    2076377600
arc_meta_max                    4    498721632
```

**Comment by GladOSkar** [comment]
Line 3 of your example didn't compile for me (no `read_to_string()` in `fs::File`), but this does and seems pretty solid to me

**Comment by ammgws** [comment]
Great. Last thing to check - is there any chance a user _wouldn't_ want the ZFS stuff to be accounted for when using `{cached}`?

If so then perhaps a new format key could be introduced instead: `{cached_zfs}` and `{cached_zfs_percent}`. Or something like that.

What do you think?

**Comment by GladOSkar** [comment]
I don't think so. The only way i know people read "cached" memory is as reclaimable, i.e. technically in use but not occupied in a way that no other process can allocate. That is exactly the way the arc cache behaves afaik, so imo there's no reason to differentiate there.

**Comment by ammgws** [comment]
Let's go with this for now then :)

**Comment by euri10** [comment]
given [this comment](https://superuser.com/questions/1137416/how-can-i-determine-the-current-size-of-the-arc-in-zfs-and-how-does-the-arc-rel): 
> Because of how ZFS on Linux is implemented, the ARC memory behaves like cache memory (for example, it is evicted if the system comes under memory pressure), but is aggregated by the kernel as ordinary memory allocations. This can lead to confusion as the system appears to have far less free memory than would be expected given the current system workload, but is normal.

I'd be tempted to call it cached memory, but I'm sure purists may think differently ;)

**Pull request merged**
