### PR TITLE
Fix inverted icons in backlight block.

### PR DESCRIPTION
**Pull request by marc0der**
The icons for the backlight block seem to be inverted. The icons show black when at it's brightest, yellow when at it's dimmest. This simply inverts them to the correct phase.

### CODE REVIEW

**Comment by atheriel** [comment]
Is it possible for you to share a screenshot of this behaviour? The icons are working as described for me already.

**Comment by marc0der** [comment]
@atheriel Sure, here they are:
* when brightness is turned up, it displays dark:
Screenshot_20191013_154630
* when brightness is turned down, it displays light:
Screenshot_20191013_154658

**Comment by GladOSkar** [comment]
This is a problem with color emoji. Black and white ones look correct. I use this in my config to invert the icons:

```
[icons]
name = "awesome"
[icons.overrides]
backlight_empty = " 🌑 "
backlight_partial1 = " 🌘 "
backlight_partial2 = " 🌗 "
backlight_partial3 = " 🌖 "
backlight_full = " 🌕 "
```

**Comment by GladOSkar** [comment]
Of course changing this globally for everyone is not an option since the majority of users still have b&w emoji. Maybe a config option somewhere?

**Comment by GladOSkar** [comment]
Related: #183

**Comment by marc0der** [comment]
Great, thanks! I'll give it a try.

**Comment by marc0der** [comment]
I gave it a try and that work for me. Thanks!

**Comment by atheriel** [comment]
Ah, I had forgotten that this has come up before. Thanks @GladOSkar!

**Pull request closed without merging**
