### PR TITLE
Fix reversed symbols in backlight module

### PR DESCRIPTION
**Pull request by rumpelsepp**
The icons for the backlight module were in the wrong order. This patch reverses them.

### CODE REVIEW

**Comment by GladOSkar** [comment]
(See #452 and #183)

This is a problem with color emoji. Black and white ones look correct. I use this in my config to invert the icons:

```
[icons]
name = "awesome"
[icons.overrides]
backlight_empty = " 🌑 "
backlight_partial1 = " 🌘 "
backlight_partial2 = " 🌗 "
backlight_partial3 = " 🌖 "
backlight_full = " 🌕 "
```

**Comment by rumpelsepp** [comment]
If I understand this correctly, then the problem is the other way round. Full moon means "full light".

**Comment by GladOSkar** [comment]
If you go by the emoji definitions, yes. But since most linux desktop users are using black-and-white emojis, for them it looks the other way around when printed bright-on-dark.

Plus, we don't want to break user's existing configurations with changes like these afaik.

**Comment by rumpelsepp** [comment]
Unfortunate. I personally consider this an upstream (= font) bug which should be fixed upstream.

**Comment by GladOSkar** [comment]
Well technically most fonts are designed for dark-on-white as when printed on paper, and then the b&w fonts are correct again. It's just a limitation of the single color font system ¯\\\_(ツ)\_/¯

**Comment by atheriel** [comment]
Indeed, this is an unfortunate ambiguity for these icons.

**Comment by Thra11** [comment]
All the rest of the icons on my status bar are monochrome, but the brightness one has recently (since 0.14.0 perhaps?) become full-colour (I have `icons = "awesome5"` in my config), which makes it "backwards" as reported in #845. Perhaps that's the issue that needs to be fixed instead of reordering them?

**Comment by GladOSkar** [comment]
The color of the icons does not depend on `i3status-rust` but rather on your system (font/pango/cairo) as far as i know. This project doesn't have control over that. More and more distros are shipping color-capable font systems so this "issue" is bound to occur for more and more people.

The only thing that could probably be done to mitigate is add a `flip-order` option or similar to make it easier to override the icon order.

As i mentioned earlier, the only reason this happens is because the monochrome icons are designed for dark-on-bright text (as with paper) and not bright-on-dark (as with most status bar themes), so the real issue is that monochrome fonts happen to adapt to text color, which never makes sense for an icon that is supposed to imply brightness.

**Comment by Thra11** [comment]
Ah. I must confess I don't really know how these icon fonts work. I assumed that the output from i3status-rust specified the font and the character to draw, in theory giving complete control over the glyph that appears, so long as the requested font is installed and covers the character in question. However, as far as I can tell, font awesome doesn't actually contain any glyphs for the phases of the moon. I'm guessing that as a result, it's falling back to a font which _does_ cover the moon phase symbols, which presumably varies from system to system, sometimes resulting in monochrome moon icons, sometimes full-colour ones.

**Comment by GladOSkar** [comment]
Yes. The `i3bar` protocol is just text, the font is specified in the bar/wm config, not by `i3status`. And afaik these icons are regular unicode emoji, not fontawesome icons. So it entirely depends on your font and the font rendering system used.

**Pull request closed without merging**
