### PR TITLE
blocks: Add function to find default battery

### LINKED ISSUE #1237: Better defaults for battery block
Perhaps it could be improved by defaulting to the first file found in `/sys/class/power_supply/` instead of being hardcoded to BAT0.

_Originally posted by @ammgws in https://github.com/greshake/i3status-rust/issues/1236#issuecomment-841609021_

### PR DESCRIPTION
**Pull request by orvij**
Resolves #1237

### CODE REVIEW

**Comment by ammgws** [comment]
Can you update the docs too?

**Comment by ammgws** [comment]
Final thing: the order is not guaranteed, is it? Should we sort it by name? Or by time created?

**Comment by orvij** [comment]
> Final thing: the order is not guaranteed, is it? Should we sort it by name? Or by time created?

Sorted by name. Still default to `BAT0` if no directory is found in `/sys/class/power_supply`. Replaces with first found dir, then with the first ordered dir past that, e.g. `BAT1` replaces `BAT2`.

**Comment by ammgws** [comment]
Alright, thanks!

**Comment by matthiaskrgr** [comment]
This broke i3status-rs for me:
````
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'byte index 3 is out of bounds of `AC`', src/blocks/battery.rs:561:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`````

`/sys/class/power_supply/` looks like this:
````
AC  BAT0  BAT1  ucsi-source-psy-USBC000:001
````

**Comment by matthiaskrgr** [comment]
The problem seems to be that `AC` only has 2 letters so the array index `&f[..3] == "BAT"` is out of bounds

**Pull request merged**
