### PR TITLE
Using `strfmt` to add partial rust stdlib formatting capabilities to blocks

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by rtxm** [comment]
Unfortunately, this requires rust-nightly and I'd prefer not to be forced to switch from rust-stable.

**Comment by ilya-epifanov** [comment]
@rtxm Noticed it quite late, unfortunately.

I like, however, how data model used by blocks looks. In some case support for modifiers allowed to remove redundant placeholders (e.g. `MUp` and `MUpi`).

**Comment by atheriel** [comment]
I'm inclined to agree that working on stable is very desirable. Is there a path to stabilization for the required features? It does make the code look much nicer.

**Comment by ilya-epifanov** [comment]
@atheriel Unfortunately, the features that `runtime-fmt` uses are far from being stabilized :( I can try switching to https://crates.io/crates/strfmt while keeping the `#derive[(FormatArgs)]`.

**Comment by ilya-epifanov** [comment]
@rtxm @atheriel Works on stable now, please review

**Comment by ilya-epifanov** [comment]
@rtxm @atheriel @greshake what do you think?

**Comment by atheriel** [comment]
I am still supportive of this PR, but it is quite complex and will take time to review. In the meantime I hope you can be patient.

**Comment by greshake** [comment]
This is a lot better than my old implementation, I'll take a look too

**Comment by ilya-epifanov** [comment]
@greshake @atheriel @rtxm I've just rebased the PR again, could you please take a look?

**Comment by ammgws** [comment]
Closing due to inactivity.

**Pull request closed without merging**
