### PR TITLE
[WIP] Possible implementation for #50

### PR DESCRIPTION
**Pull request by svmnotn**
I've implemented it for pacman, battery, and temperature.

This is just a quick test of concept, feel free to comment & test.
@michelboaventura please test this in your setup to see if it works well for it.

### CODE REVIEW

**Comment by svmnotn** [comment]
@keeslinp @jheyens any ideas/comments about this impl?

**Comment by keeslinp** [comment]
I'm probably not a good authority on best rust practices so I'm genuinely curious not criticizing. Is a vector of pending deletions the idiomatic way to remove things from a vector while mapping through it? Seems like a smart way to side-step the borrow-checker issues to me.

**Comment by svmnotn** [comment]
@keeslinp altering a collection while stepping through it can cause issues (and it neatly avoids issues with the borrow checker ;) )

**Comment by keeslinp** [comment]
@svmnotn Yeah, I've done that battle a few times so I was intrigued by that neat solution. Thanks :).

**Comment by svmnotn** [comment]
I'm going to close this in favor of @greshake proposal of profiles in #50

**Pull request closed without merging**
