### PR TITLE
Auto-generate man pages from markdown

### PR DESCRIPTION
**Pull request by crablab**
As in #380, generate proper man pages from the markdown. 

Nb. this generates the man page at CI. Still clarifying how we want to 'deloy' it...

### CODE REVIEW

**Comment by crablab** [comment]
So it [looks like](https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/11) Travis doesn't run CI on draft PRs :cry:

**Comment by greshake** [comment]
Should we maybe add a simple pandoc man page generator script for local builds? Then we can push a static version with every tagged release. I don't want to push the pandoc dependency on to the people building the packages

**Comment by atheriel** [comment]
I'd prefer that approach. I don't think this PR goes far enough, and it made me think that we need to actually write a man page, or at least sections of it.

**Comment by greshake** [comment]
Unfortunately our cmdline interface library doesn't support generating man pages yet :( https://github.com/clap-rs/clap/issues/552

**Comment by crablab** [comment]
This PR was never meant to be particularly great :man_shrugging:  

I'm not really sure what direction the maintainers would like to take here. I feel like clap supporting man page generation would be the best solution, but that doesn't seem like it's coming anytime soon.

**Comment by atheriel** [comment]
@crablab To be clear, I did not intend to attack you or the quality of your submission. I just think the scope of this issue is larger than what can be solved using the existing documentation, mostly because a proper man page would need to include sections that simply have not been written yet.

**Comment by crablab** [comment]
@atheriel Oh yeah for sure :blush:  Offence was never taken! I generally agree - my comments are simply that I don't really know what direction people want to take here. 
The problem with manually writing manpages is they quickly tend to get out of sync with developments in the project.

**Comment by atheriel** [comment]
#556 should fulfill the ideas in this PR. Thanks for your work!

**Pull request closed without merging**
