### PR TITLE
Added a block for tracking bitcoin value in multiple currencies

### PR DESCRIPTION
**Pull request by ThyW**
This PR adds Bitcoin tracking in multiple currencies(list available [here](https://www.blockchain.com/ticker)). 

Configuration looks like this:

```toml
[[block]]
block = "btc"
interval = 10 # (default is 60 seconds)
currency = "EUR" # (default is USD)
currency_list = ["EUR", "USD", "RUB", "CNY"] # (default is just USD)
```
To switch between the currencies, you can just scroll down on the text.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
```toml
[[block]]
block = "custom"
command = ''' echo 1B = $(curl -s https://blockchain.info/ticker | jq '.EUR.last')€ '''
```

Isn't this enough?

**Comment by ammgws** [comment]
Thanks for your contribution! Unfortunately we prefer Custom blocks to be used where possible in order to reduce maintainer burden. As discussed in #715 it may be a good idea to have a "custom block example repository" that people could contribute to. Perhaps in the Wiki?

**Comment by MaxVerevkin** [comment]
> Perhaps in the Wiki?

I think it is still impossible to contribute to the Wiki. So maybe `examples/custom`?

**Comment by MaxVerevkin** [comment]
@ammgws If we do not accept this kind of blocks, functionality of which can be easily achieved using a `custom` block, then why do we have `uptime`???

**Comment by ammgws** [comment]
See https://github.com/greshake/i3status-rust/pull/141

Also something like `uptime` is not likely to break compared to this which relies on an online service.

**Comment by hjco** [comment]
Thanks @MaxVerevkin I added  bitcoin price custom block.

`[[block]]
block = "custom"
command = ''' echo  $(curl -s https://api.coindesk.com/v1/bpi/currentprice/usd.json | grep -o 'rate":"[^"]*' | cut -d\" -f3) USD '''
interval = 10`

2024-11-09-21:22:16-screenshot

**Pull request closed without merging**
