### PR TITLE
focused_window block: show marks with brackets like sway does

### PR DESCRIPTION
**Pull request by ammgws**
Resolves https://github.com/greshake/i3status-rust/pull/532#issuecomment-581854186

@travankor

### CODE REVIEW

**Comment by travankor** [comment]
I don't know rust, but I think there might be a regression here. `focused_window` stopped updating after this.

**Comment by travankor** [comment]
Seems like if you focus a marked window, the whole bar freezes and stops updating.

**Comment by ammgws** [comment]
Argh I thought I had tested it already. I'll check it out

**Comment by ammgws** [comment]
OK so I could reproduce that the focused_window block stops updating, but the rest of the bar/blocks still keep updating.

**Comment by travankor** [comment]
To get the whole bar to freeze: 

1) open two terminals
2) `swaymsg mark 123` on one terminal
3) keep changing focus and the bar will freeze

**Comment by ammgws** [comment]
Yeah that's what I did. Tried it again and still the same - only the focused_window block stops updating.

**Pull request merged**
