### PR TITLE
Enable clippy linting in travis

### PR DESCRIPTION
**Pull request by carloabelli**
See #663.

### CODE REVIEW

**Comment by ammgws** [comment]
Can you move those code changes to another PR so we can keep this one just about the CI itself?

**Comment by carloabelli** [comment]
@ammgws Sounds good. Once this is merged, I can put up another PR enabling the checks for --all-targets and --all-features (this requires some code changes to pass). Unless you would prefer to merge the code changes in first and then update this PR to include --all-targets and --all-features?

**Comment by carloabelli** [comment]
One other thing to consider is how we want to handle clippy warnings. One possibility (the one currently implemented) is to fail on any warning (which will also fail for rustc warnings). The current script does not fail on rustc warnings so perhaps that is undesirable? Another solution is to make all the default clippy warnings errors, which will allow rustc warnings through, but fail for clippy warnings. Finally we can just ignore all warnings altogether.

**Comment by ammgws** [comment]
Now that all the lints have been fixed, perhaps we could go for your suggestion as it would help keep future code in check as you mentioned.

**Comment by carloabelli** [comment]
Okay in that case this PR should be good to go then

**Pull request merged**
