### PR TITLE
Add new icon set: Material Design Icons

### PR DESCRIPTION
**Pull request by draoncc**
> **Note**: This requires a patched version of MaterialIcons-Regular.ttf as offered by Google to include \u{0020} (space), set a descent and lower all glyphs to properly align.

(This is my first pull request, so feedback is more than welcome!)

### CODE REVIEW

**Comment by greshake** [comment]
Thanks for your help! Could you extend the README to include the new requirements for the theme? You can add a new `Themes` section if you want :)

**Comment by draoncc** [comment]
Will do once I've got some free time. :) As for the required patch to the icon font, should I make a separate gist for the script or include it in this repo?

**Comment by greshake** [comment]
Hmm, you should probably distribute the patched font somewhere else, and add the needed information to the README / link to the font there.

**Comment by greshake** [comment]
Hey, any update?

**Comment by draoncc** [comment]
Hey, sorry, life has been incredibly busy. I'll get to it this week since I finally got some days off that I can spend on private projects.

**Comment by greshake** [comment]
Thanks for the update! For similar reasons I can only promise to merge soon, still a few other things on my plate..

**Comment by draoncc** [comment]
Resolved the README conflict and now all should be good. I didn't write a script to patch the Material icon font, but having the latest font patched should suffice for the time being.

**Comment by greshake** [comment]
Thanks!

**Pull request merged**
