### PR TITLE
backlight: Add option to hide if no backlight supported

### PR DESCRIPTION
**Pull request by BourgondAries**
I'm using this feature on multiple machines, both laptops and stationary. I do not want different configuration files for these systems, however, backlight will fail on reading the backlight device directory on systems without backlight, yielding an ugly red error message.

This commit allows one to hide the backlight bar if that happens.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
You can get the same result with

```toml
error_format = ""
```

**Comment by ammgws** [comment]
Or use "if_command"

**Comment by BourgondAries** [comment]
@MaxVerevkin @ammgws Oh didn't know these existed! Thanks.

**Comment by ammgws** [comment]
Let us know your final block config since could be useful for others who come across the same problem

**Comment by BourgondAries** [comment]
> Let us know your final block config since could be useful for others who come across the same problem

```
[[block]]
block = "backlight"
format = " $icon {$brightness.eng(4) |}"
error_format = ""
```

I think `error_format` just wasn't easily discoverable for me, to me it was in a sea of global configs, while I was looking inside the block's specific config. I think I did this because I saw `[icons] table:` in the readme and skipped over the visually grouped-looking "block" of content (including the error_format section) straight to `Further documentation:`.

**Pull request closed without merging**
