### PR TITLE
Implement `timezone` option for `time`.

### PR DESCRIPTION
**Pull request by derekdreery**
For your consideration :)

**EDIT** I should probably give my use case:

I have this in my config (with the PR branch)

```toml
[[block]]
block = "time"
interval = 5
format = "%a %y-%m-%d %R"

[[block]]
block = "time"
interval = 5
timezone = "US/Pacific"
format = "Pacific: %R"
```

I'm from UK, and I want to know if I can hassle ppl in SF etc. :P

### CODE REVIEW

**Comment by derekdreery** [comment]
PS this library is really great, and really fun to hack on! :)

**Comment by atheriel** [comment]
This is a nice addition, thank you. Do you happen to know if it fixes #169?

**Comment by derekdreery** [comment]
I would think Not, sadly. The crate this comes from is `time` - that would
be the place to start looking.

**Comment by atheriel** [comment]
I'm happy to merge this in either case, just let me know when you feel it's complete.

**Comment by derekdreery** [comment]
I think it's pretty much there now.

**Comment by danihodovic** [comment]
Excellent! Thanks @derekdreery !

**Pull request merged**
