### PR TITLE
Battery block: ability to calculate remaining time from charge/current

### PR DESCRIPTION
**Pull request by GladOSkar**
Remaining time didn't work for me, because my machine doesn't have the `energy_now` and `power_now` files but only `charge_now` and `current_now`.

This makes it so that `energy/power` is used if available, then if not, `charge/current` is used, and if neither is present, an error is thrown.

I am relatively new to rust, let me know if i've done something suboptimally :)

### CODE REVIEW

**Comment by atheriel** [comment]
This looks good to me. Do you find that it gives a reasonable estimate of the time remaining?

**Comment by GladOSkar** [comment]
@atheriel It gives a reasonably good, usable estimate. I never really measured how much it deviates from actual discharge times. Maybe i'll do that some time.

**Comment by GladOSkar** [comment]
OK I did some science to it:

ert-measurements

The current implementation varies a lot depending on the current power usage and basically isn't averaged at all. But even if averaged over 10 minutes (see green line), it does not give a consistent trajectory.

The charge line on the other hand is surprisingly consistent, so i would recommend calculating the remaining time by averaging over charge amounts.

The averaging interval should probably be between 2 and 10 minutes, maybe customizable with 5 minutes as a default?

**Comment by atheriel** [comment]
That's excellent investigative work, thank you. I'll file a follow-up issue.

**Pull request merged**
