### PR TITLE
[WIP] Factor code to check block id when clicked

### PR DESCRIPTION
**Pull request by leowzukw**
Implement [this comment](https://github.com/greshake/i3status-rust/issues/249#issuecomment-419442576) from #249.

We want to factor the code called for each block, that checks whether the block was clicked or not.

- [x] Refactor `click` to `click_any`.
- [ ] Add the new `click` method, relaying click inside the block only.
- [ ] Use this new method in blocks where it makes sense.

### CODE REVIEW

**Comment by greshake** [comment]
This PR should be joined with the implementation of the new click method that only relays clicks on the same block

**Comment by leowzukw** [comment]
If the `click` function from 69941f0 is what you want, I could start to use it instead of `click_any` in some block.

**Comment by greshake** [comment]
Yea that's it, my bad :D

**Comment by greshake** [comment]
Just noticed: The problem is that the event name isn't the same as the block id. Since any block can have multiple widgets (like the play/pause buttons on the music block) the event name matches the widget id instead, so we'd need to know which widgets belong to which block

**Comment by leowzukw** [comment]
I will have a look at this.

**Comment by leowzukw** [comment]
Finally found time to work on this.

So, I’m not sure to follow, you want me to add a method to block to get a list of each widget id in that block? Or should we use the click method for any block with widget?

**Comment by leowzukw** [comment]
ping @greshake ?

**Comment by leowzukw** [comment]
Poke poke 😄

**Pull request closed without merging**
