### PR TITLE
Highlight "net" module when tx/rx speed is above thresholds

### PR DESCRIPTION
**Pull request by jypma**
I've been using `i3status-rust` for a while with great pleasure, and felt that it would be nice if the "net" module highlights itself when the network is used (just like the CPU or Load modules).

This PR adds the ability for the "net" module to highlight itself in info/warning/error colors, depending on the rx or tx speed exceeding certain thresholds.

There are a few things that aren't quite done yet, though:
- [ ] Thresholds should be configurable (I can add this shortly)
- [x] ~Right now, only the text section of the "net" module lights up. The icon itself doesn't. This is different from the CPU or Temperature modules, where both the icon and text light up. I'm not sure what causes this difference.~

Any feedback / help is appreciated :-)

### CODE REVIEW

**Comment by GladOSkar** [comment]
The second point is because the net block has the icon on a separate widget from the mail text. Colors are only applied to a single widget in your case. Solutions would include a) moving the icon into the main widget (with format string placeholder?) or b) applying the same color to the icon widget.

**Comment by ammgws** [comment]
There's also this request: https://github.com/greshake/i3status-rust/issues/397 (which makes more sense to me)

**Comment by GladOSkar** [comment]
> There's also this request: #397 (which makes more sense to me)

That can probably be integrated into this one as an option

**Comment by jypma** [comment]
Thanks for the feedback! Both widgets are now updated. As to incorporating #397, I have a few ideas:
- Have the proposed configuration options `info_speed`, `warn_speed` and `critical_speed` with the bytes/sec _above_ which the status would be set (defaulting to `u32::MAX`).
- Have additional options `info_signal_strength`, `warn_signal_strength` and `critical_signal_strength` with the percentage _below_ which the status would be set (defaulting to `0`).
- The actual status picked would be higher one of the above.

This would cover most cases, except being able to display a wired connection link being up or down. For that, we could add a third option:
- Have a setting `inactive_status`, which can be `idle`, `info`, `warn` or `critical`, which is enabled when that `[[net]]` section is not active (defaulting to `idle`).

There's potentially a lot of configuration options in here... do we go for all of them?

**Comment by jypma** [comment]
If there's no further feedback, I'll try and implement all configuration options when I get some time.

**Comment by ammgws** [comment]
I wonder if it's possible to keep the format string option but reintroduce the widgets that were removed when the format string was implemented and then have per widget state/colours instead.

**Comment by ammgws** [comment]
Looks like we should be able to do this by doing something like https://github.com/greshake/i3status-rust/commit/714b29f1f0244c976780a0bf9c35c8fe9bbd6149

**Comment by GladOSkar** [comment]
@MaxVerevkin already mentioned that he doesn't really like the `render_widgets()` function from that commit and i think i agree, it's not that nice and barely any blocks need/use it. I actually removed it in #1207 after we decided `speedtest` doesn't need it anymore.

So I'd say just including the icon in the main widget is the best solution here IMO.

**Comment by MaxVerevkin** [comment]
@GladOSkar
> But we could also reintroduce that function if it's worth the extra effort

We can reintroduce but we will lose "short text" functionality for some blocks that would use it. Auto-hiding is much more valuable than highlighting if you ask me (in particular for net block).

So I suppose the only way to have "per widget" highlighting is to use pango, but as discussed earlier, i3 and sway renders it differently.

**Comment by MaxVerevkin** [comment]
Closing due to lack of activity

**Pull request closed without merging**
