### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jeremystucki**

### CODE REVIEW

**Comment by ammgws** [comment]
Are those patterns that you refactored present in other blocks as well?

**Comment by jeremystucki** [comment]
I can have a look tonight. These changes just come from me wondering how the music block works

**Comment by m-hugo** [comment]
did you test this?  you used max( instead of min(

**Comment by jeremystucki** [comment]
You're totally right

**Comment by ammgws** [comment]
Rebase?

**Comment by jeremystucki** [comment]
There are too many conflicts. I'll create a new PR sometime

**Pull request closed without merging**
