### PR TITLE
Docs: Update docs with xprofile envs

### PR DESCRIPTION
**Pull request by benmezger**
Add missing steps on adding env for i3 to be able to read from.

### CODE REVIEW

**Comment by ammgws** [comment]
Hmm I'm not too sure about this, especially since there are several ways of achieving this aside from using .xprofile.

**Comment by benmezger** [comment]
Trying to set in `.xprofile` here didn't work :(

**Comment by benmezger** [comment]
Which ways? I was only able to get it working with =.xprofile=, but I would be happy to update this documentation if that's the case

**Comment by ammgws** [comment]
Consider the simplest scenario in which you boot straight into a login shell and run i3 via `startx` from the command line. All you need is for the environment variables to be exported in the shell before you run `startx`, and then i3 should inherit them when it starts. In this case, there are many ways of setting the env vars: in your shell's init file (e.g. `~/.bash_profile`), `~/.xinitrc`, or probably even `~/pam_environment`. In your case I take it you are using some kind of display manager instead of booting into a shell, and it seems like `~/.xprofile` is required for the one you're using.

**Pull request closed without merging**
