### PR TITLE
kdeconnect: detect disconnections

### PR DESCRIPTION
**Pull request by ammgws**
See https://github.com/greshake/i3status-rust/pull/717#issuecomment-638152064

Haven't tested yet but it should work assuming the "reachable" flag supplied by kdeconnect is accurate.

### CODE REVIEW

**Comment by GladOSkar** [comment]
Doesn't work on my machine:

image

**Comment by ammgws** [comment]
Yeah I haven't dealt with that situation yet. This just changes the icon when the phone becomes 'unreachable' while the bar is running.

**Comment by GladOSkar** [comment]
Ah alright. Yeah as someone who shuts down and starts his computer many times a day when not at home, this is not really usable then

**Comment by ammgws** [comment]
Try setting your `device_id` in the config.

I disconnected my phone from the network and started i3status-rust, and it somehow returned the last known values for the device. Then when I reconnected the phone it started updating as usual. Need to test with a fully cold start as well but at least that's a step forward I guess?

**Comment by ammgws** [comment]
OK so as a test I just pushed some changes so that it doesn't crash the bar when the device supplied in the config is not found at startup.

image

However it's not updating even after I connected the phone so I need to look into it a bit more

**Comment by GladOSkar** [comment]
> I disconnected my phone from the network and started i3status-rust, and it somehow returned the last known values for the device.

Yeah in my case it also took about a minute until `kdeconnectd` even realized the phone was gone. During that period, the bar would still start up successfully, afterwards not anymore. Actually, sometimes `kdeconnectd` doesn't seem to notice the disconnect at all.

With the device ID, startup detection works, but if i then connect my phone to the network, it doesn't show when kdeconnect connects to the device.

**Comment by GladOSkar** [comment]
Also, when disconnected, can we just not show device information and instead _just_ the "Not connected" icon? Might be less confusing

**Comment by ammgws** [comment]
I was hoping there would be some activity on the bus when the phone reconnects but somehow there's nothing... Checked both `busctl --user monitor org.kde.kdeconnect` and `busctl --user monitor org.kde.kdeconnect.daemon`. Would hate to have to add a manual update interval for this.

**Comment by GladOSkar** [comment]
Oh i guess i got confused by the icon not updating then. Will test again now

**Comment by GladOSkar** [comment]
BTW, missing semicolon on line 146 :P

**Comment by ammgws** [comment]
I ended up adding another format string to choose what to display when the phone is disconnected.

**Comment by ammgws** [comment]
> Works perfectly

Hmm, it still doesn't recover if you disconnect the phone while the bar is running. I'll merge this for now as it's better than what we have now, and in the meantime I will see what else I can do.

**Comment by GladOSkar** [comment]
> Hmm, it still doesn't recover if you disconnect the phone while the bar is running. I'll merge this for now as it's better than what we have now, and in the meantime I will see what else I can do.

In my case it still sometimes does detect it and sometimes doesn't, but that's just because kdeconnect apparently doesn't even notice

**Pull request merged**
