### PR TITLE
formatting: implement named arguments instead of positional

### LINKED ISSUE #1605: Maybe reconsider formatter arguments?
Currently positional arguments are used for formatters (e.g. `$num.eng(3,auto,K)`), but I think it's better to discuss this one more time before 0.30 release.

Positional arguments generally work fine, especially for simple cases like `$num.eng(2)` or `$text.rot-str(20)` (but not `$text.str(20)`!). However, it gets a bit weird when all you want is to enable "binary prefixes", such as `"$available.eng(3,auto,1i)"`. Wouldn't `$available.eng(bin:true)` be more clear? But then again, `$num.eng(5,b,Ki)` is way less verbose than `$num.eng(width:5,unit:b,prefix:K,bin:true)`.

One solution can be to mix those two (python style). Most common usecases might only use first positional arguments, while others might require named parameters.

For example, let's take `eng` formatter. It may have the following arguments:
- `width` (number)
- `unit` (Unit)
- `min_prefix` (Prefix)
- `max_prefix` (Prefix)
- `insert_space` (boolean)
- `bin` (boolean)

The positional arguments might be defined in this order: `width`, `unit`, `min_prefix`.

Then this | would mean this
--------------|-------------------------
`.eng(3)` | `width = 3`
`.eng(3,bin:true)` | `width = 3`, `bin = true`
`.eng(min_prefix:K)` | `min_prefix = 3`

This allows for better extensibility in the future. New features can be activated via new named arguments instead of modifiers for existing arguments.

### LINKED ISSUE #1624: Formatting: `rot-str`: add an option to disable padding

### LINKED ISSUE #1655: pango escaping on by default?
At some point recently it seems like escaping pango characters has been added to format strings by default, but as far as I can tell it breaks being able to use pango formatting in the first place.

e.g. a custom block that outputs `"<span color='red'>my custom text here</span>"` is pango escaped so displays literally in the bar without being rendered by pango
```json
{"full_text":"","color":"#424242FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" &lt;span color=&#39;red&#39;&gt;my custom text here&lt;/span&gt; ","color":"#FFFFFFFF","background":"#424242FF","name":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Closes #1605
Closes #1624
Closes #1655

```toml
format = " $speed_down.eng(3,_B,K) $frequency.eng(4) $ssid.rot-str(10,0.2) "
```

Becomes

```toml
format = " $speed_down.eng(w:3,p:K,hide_unit:true) $frequency.eng(w:4) $ssid.str(max_w:10, rot_interval:0.2) "
```

Also use `nom` for parsing. The downside of this is that error messages are even worse now. But this should be fixable.

### CODE REVIEW

**Comment by GladOSkar** [comment]
I think i liked the old, concise version better. But this seems fine as well, not gonna die on that hill

**Comment by MaxVerevkin** [comment]
> I think i liked the old, concise version better.

The old version is nice, simple and compact, but it is also not extensible. For example I don't know how to implement `$x.str(pango:true)` with it, apart from introducing a dedicated formatter which behaves like `str` but does not escape pango. Also hacks like ` _B` for "hidden bytes with a space" are questionable (but compact, which is nice).

Speaking about dedicated formatters, with this new syntax `rot-str` can be merged into `str` by adding "rot_interval" argument to `str`. This would close #1624.

**Comment by MaxVerevkin** [comment]
>  I don't know how to implement $x.str(pango:true) with it, apart from introducing a dedicated formatter which behaves like str but does not escape pango

On a second thought, making it a separate formatter seems like a good idea because min/max width and rotating doesn't work for unescaped pango anyway.

**Comment by ammgws** [comment]
Seems good so far

**Comment by MaxVerevkin** [comment]
I'll mark this PR as ready once I fix error reporting.

**Review by ammgws — APPROVED** [review]

**Pull request merged**
