### PR TITLE
introduce `debug_borders` feature

### PR DESCRIPTION
**Pull request by MaxVerevkin**
If compiled with `--features debug_borders`, the bar will look like this:
image

Useful for debugging issues with spacing.

### CODE REVIEW

**Comment by ammgws** [comment]
Interesting idea!

**Comment by MaxVerevkin** [comment]
Added a link to https://github.com/rust-lang/rust/issues/15701

**Comment by MaxVerevkin** [comment]
The implementation will be cleaner with #1085 merged.

**Comment by ammgws** [comment]
Hopefully this can come in handy later.

Cheers!

**Pull request merged**
