### PR TITLE
Info about colors

### PR DESCRIPTION
**Pull request by asdf8dfafjk**

### CODE REVIEW

**Comment by ammgws** [comment]
Feel free to submit a PR that allows colours to be set. 
See also https://github.com/greshake/i3status-rust/issues/580

**Comment by ammgws** [comment]
It feels kind of out of place in the main readme. It might be better for themes.md

**Comment by ammgws** [comment]
@asdf8dfafjk You may like to try #947 as it should enable you to customise colours as you like.

**Comment by asdf8dfafjk** [comment]
Thank you.

**Pull request closed without merging**
