### PR TITLE
Add start_separator

### PR DESCRIPTION
**Pull request by lorber13**
Linked to issue #2066

### CODE REVIEW

**Comment by bim9262** [comment]
@siddarth2810 raises a good point on the issue, the color for the start separator should match the first segment of the first block.

<details>
<summary>Something like...</summary>

```diff
diff --git a/src/protocol.rs b/src/protocol.rs
index df6007ff0..5ee8877b1 100644
--- a/src/protocol.rs
+++ b/src/protocol.rs
@@ -25,11 +25,17 @@ where
     let mut prev_last_bg = Color::None;
     let mut rendered_blocks = vec![];
 
-    // The right most block should never be alternated
-    let mut alt = blocks
+    let blocks_with_segments: Vec<RenderedBlock> = blocks
         .iter()
         .map(|x| x.borrow())
-        .filter(|x| !x.segments.is_empty() && !x.merge_with_next)
+        .filter(|x| !x.segments.is_empty())
+        .cloned()
+        .collect();
+
+    // The right most block should never be alternated
+    let mut alt = blocks_with_segments
+        .iter()
+        .filter(|x| !x.merge_with_next)
         .count()
         % 2
         == 0;
@@ -42,17 +48,21 @@ where
         rendered_blocks.push(I3BarBlock {
             full_text: start_separator.clone(),
             background: Color::None,
-            color: prev_last_bg,
+            // Peek at the first segment of the first first block to see what color it is
+            color: blocks_with_segments.first().map_or(Color::None, |widget| {
+                widget.segments.first().map_or(Color::None, |segment| {
+                    if alt {
+                        segment.background + config.theme.alternating_tint_bg
+                    } else {
+                        segment.background
+                    }
+                })
+            }),
             ..Default::default()
         });
     }
 
-    for widgets in blocks
-        .iter()
-        .map(|x| x.borrow())
-        .filter(|x| !x.segments.is_empty())
-        .cloned()
-    {
+    for widgets in blocks_with_segments {
         let RenderedBlock {
             mut segments,
             merge_with_next,
```

</details>

**Comment by bim9262** [comment]
Both your code and what I wrote yesterday don't replace the first separator, but just add another in front, but perhaps it would be better to replace it with the specified separator like

`<start separator, if set, else separator><block 1><separator><block 2>...<end separator, if set>`

**Comment by siddarth2810** [comment]
if its alright, I can take this up :)

**Comment by lorber13** [comment]
> Both your code and what I wrote yesterday don't replace the first separator, but just add another in front, but perhaps it would be better to replace it with the specified separator like
> 
> `<start separator, if set, else separator><block 1><separator><block 2>...<end separator, if set>`
> Perhaps
> 
> ```diff
> diff --git a/src/protocol.rs b/src/protocol.rs
> index df6007ff0..72e774701 100644
> --- a/src/protocol.rs
> +++ b/src/protocol.rs
> @@ -38,20 +38,12 @@ where
>  
>      let mut prev_merge_with_next = false;
>  
> -    if let Separator::Custom(start_separator) = &config.theme.start_separator {
> -        rendered_blocks.push(I3BarBlock {
> -            full_text: start_separator.clone(),
> -            background: Color::None,
> -            color: prev_last_bg,
> -            ..Default::default()
> -        });
> -    }
> -
> -    for widgets in blocks
> +    for (i, widgets) in blocks
>          .iter()
>          .map(|x| x.borrow())
>          .filter(|x| !x.segments.is_empty())
>          .cloned()
> +        .enumerate()
>      {
>          let RenderedBlock {
>              mut segments,
> @@ -73,7 +65,12 @@ where
>              alt = !alt;
>          }
>  
> -        if let Separator::Custom(separator) = &config.theme.separator {
> +        let separator = match &config.theme.start_separator {
> +            Separator::Custom(_) if i == 0 => &config.theme.start_separator,
> +            _ => &config.theme.separator,
> +        };
> +
> +        if let Separator::Custom(separator) = separator {
>              if !prev_merge_with_next {
>                  // The first widget's BG is used to get the FG color for the current separator
>                  let sep_fg = if config.theme.separator_fg == Color::Auto {
> ```

Why do we need a start separator if the default separator is already present before the first block? I'm starting to have doubts about its usefulness.

**Review by MaxVerevkin — CHANGES_REQUESTED** [review]
Does not currently work as expected, please apply @bim9262's suggestion.

**Review by MaxVerevkin — APPROVED** [review]

**Pull request merged**
