### PR TITLE
Added hint on Maildir block documentation

### PR DESCRIPTION
**Pull request by theamma**
I just added a hint that feature enabling is necessary for the _Maildir_ block (analog to _notmuch_ doc)

### CODE REVIEW

**Review by ammgws — APPROVED** [review]

**Comment by MaxVerevkin** [comment]
@theamma could you please resolve merge conflicts?

**Comment by theamma** [comment]
Sorry, I'm not very familar with this. I fetched all commits on my forked repo. The conflicts should be resolved now.

**Comment by MaxVerevkin** [comment]
Looks like by merging the latest changes you've overridden your original commit. And there are still conflicts...

**Comment by MaxVerevkin** [comment]
Thanks! And it's interesting that I was able to merge without any conflicts from Android app but not from browser...

**Pull request merged**
