### PR TITLE
Fix typos, correct icon names for sound block

### PR DESCRIPTION
**Pull request by danielrainer**
Also removes trailing whitespace from `doc/blocks.md`.

### CODE REVIEW

**Comment by GladOSkar** [comment]
The double trailing spaces `  ` are semantic in markdown, they indicate a line break. Not sure if you intended to remove those.

**Comment by danielrainer** [comment]
> The double trailing spaces are semantic in markdown, they indicate a line break. Not sure if you intended to remove those.

Thank you for letting me know, I did not intend to change the formatting. Trailing double spaces are restored in 270ef473507503223a5422ac02e5ac5f20fa33e7.

**Review by GladOSkar — APPROVED** [review]
lgtm

**Comment by ammgws** [comment]
Thanks!

**Pull request merged**
