### PR TITLE
Refactor icons deserialization and add ability to load icons from file

### PR DESCRIPTION
**Pull request by MaxVerevkin**
### Changes
- With this PR it is now possible to load icons from a separate file, just like themes
- User can omit `.toml` extension when loading a theme or an icon set from a file
- All this takes 27 lines less compared to previous implementation!

### TODO
- [x] Write documentation
- [ ] Probably some testing is necessary

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Also, this PR makes it possible to separate theme/icon data and the actual code by always reading themes/icons from file. I don't know the details of packaging, but having `/usr/share/i3status-rust/icons/awesome.toml` instead of hard-coded icons is better in terms of code organization (IMO). This idea is open to discussion and I'll open a new issue once this PR is merged.

**Comment by ammgws** [comment]
From a quick look this seems OK. Just need to update the docs.

**Comment by MaxVerevkin** [comment]
> Just need to update the docs.

Done.

**Comment by ammgws** [comment]
Thanks! I haven't had time to test it personally but you've got my trust.

**Pull request merged**
