### PR TITLE
Add PiHole block

### PR DESCRIPTION
**Pull request by EugeneKorshenko**
New block for monitoring PiHole server (https://pi-hole.net project) as suggested here https://github.com/greshake/i3status-rust/issues/715. Clones appropriate _bumblebee-status_ extension.

P.S.: This is my first Rust code, so please don't throw tomatoes a lot :smile:

### CODE REVIEW

**Comment by ammgws** [comment]
> as suggested here #715.

Sorry if there was any confusion, however that was only a list of blocks from other status programs. As discussed over there, for blocks such as this one I believe they are trivial enough to be implemented using a Custom or Toggle block.

**Comment by ammgws** [comment]
Thanks anyway!

**Comment by EugeneKorshenko** [comment]
@ammgws Thanks. Sorry, generally agree, that this block can be relatively easily implemented via Custom block.

**Comment by EugeneKorshenko** [comment]
@ammgws Sure. Here is a PR: #1226

**Pull request closed without merging**
