### PR TITLE
Add new emoji icon set 🙂

### PR DESCRIPTION
**Pull request by bim9262**
Only half serious about this...

### CODE REVIEW

**Comment by ammgws** [comment]
Are you actually using this by any chance?

**Comment by bim9262** [comment]
No, I'm not using this. I just did it for fun/to see if it would spur a conversation. I had been using awesome6, but just switched to material-nf (I am using #1728).

**Comment by GladOSkar** [comment]
I kinda like it as an alternative that doesn't require installing external fonts. Should probably try to find some emoji for the last couple of icons though.

**Comment by bim9262** [comment]
> I kinda like it as an alternative that doesn't require installing external fonts. Should probably try to find some emoji for the last couple of icons though.

I finished fleshing out the icon set :)

**Comment by GladOSkar** [comment]
Haha i love the choices, especially the combinations :D

**Review by MaxVerevkin — APPROVED** [review]
I finally tried it and it looks interesting :)

**Comment by bim9262** [comment]
@MaxVerevkin, just added in a few new icons for night weather + fog + moon.

**Comment by bim9262** [comment]
Oh I just noticed emoji and all of the awesome fonts have the backlight backward from materia{,-nf}...

I'll fix emoji here and create a seperate PR for the awesome icons sets.

**Comment by bim9262** [comment]
Reverting changes to the brightness icons per #1942

**Review by MaxVerevkin — APPROVED** [review]

**Pull request merged**
