### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by michelboaventura**
Before:
```Bash
$ cargo outdated
Name                                  Project  Compat   Latest   Kind         Platform
----                                  -------  ------   ------   ----         --------
aho-corasick->memchr                  2.0.1    2.2.1    2.2.1    Normal       ---
ansi_term->winapi                     0.3.4    0.3.8    0.3.8    Normal       cfg(target_os = "windows")
atty->libc                            0.2.59   0.2.62   0.2.62   Normal       cfg(unix)
atty->termion                         1.5.1    Removed  Removed  Normal       cfg(target_os = "redox")
atty->winapi                          0.3.4    0.3.8    0.3.8    Normal       cfg(windows)
backtrace->backtrace-sys              0.1.16   0.1.31   0.1.31   Normal       ---
backtrace->cfg-if                     0.1.3    0.1.10   0.1.10   Normal       ---
backtrace->libc                       0.2.59   0.2.62   0.2.62   Normal       ---
backtrace->rustc-demangle             0.1.8    0.1.16   0.1.16   Normal       ---
backtrace-sys->cc                     1.0.15   1.0.45   1.0.45   Build        ---
backtrace-sys->libc                   0.2.59   0.2.62   0.2.62   Normal       ---
chrono                                0.4.2    0.4.9    0.4.9    Normal       ---
chrono->num-integer                   0.1.36   0.1.41   0.1.41   Normal       ---
chrono->num-traits                    0.2.3    0.2.8    0.2.8    Normal       ---
chrono->time                          0.1.40   0.1.42   0.1.42   Normal       ---
chrono-tz                             0.4.1    ---      0.5.1    Normal       ---
chrono-tz->chrono                     0.4.2    0.4.9    0.4.9    Normal       ---
chrono-tz->parse-zoneinfo             0.1.1    ---      0.2.0    Build        ---
clap                                  2.31.2   2.33.0   2.33.0   Normal       ---
clap->atty                            0.2.10   0.2.13   0.2.13   Normal       ---
clap->bitflags                        1.0.3    1.2.0    1.2.0    Normal       ---
clap->strsim                          0.7.0    0.8.0    0.8.0    Normal       ---
clap->textwrap                        0.9.0    0.11.0   0.11.0   Normal       ---
clap->unicode-width                   0.1.4    0.1.6    0.1.6    Normal       ---
clap->vec_map                         0.8.0    0.8.1    0.8.1    Normal       ---
crossbeam-channel                     0.3.8    0.3.9    0.3.9    Normal       ---
crossbeam-channel->crossbeam-utils    0.6.5    0.6.6    0.6.6    Normal       ---
crossbeam-channel->smallvec           0.6.9    Removed  Removed  Normal       ---
crossbeam-utils->cfg-if               0.1.3    0.1.10   0.1.10   Normal       ---
crossbeam-utils->lazy_static          1.3.0    1.4.0    1.4.0    Normal       ---
dbus                                  0.6.1    0.6.5    0.7.1    Normal       ---
dbus->libc                            0.2.59   0.2.62   0.2.62   Normal       ---
dbus->libdbus-sys                     0.1.3    0.2.1    0.2.1    Normal       ---
fuchsia-zircon->bitflags              1.0.3    Removed  Removed  Normal       ---
fuchsia-zircon->fuchsia-zircon-sys    0.3.3    Removed  Removed  Normal       ---
i3ipc                                 0.8.2    0.8.4    0.10.1   Normal       ---
i3ipc->byteorder                      1.2.2    1.3.2    1.3.2    Normal       ---
i3ipc->log                            0.3.9    ---      0.4.8    Normal       ---
i3ipc->serde                          1.0.53   1.0.101  1.0.101  Normal       ---
i3ipc->serde_json                     1.0.17   1.0.40   1.0.40   Normal       ---
inotify                               0.5.1    ---      0.7.0    Normal       ---
inotify->bitflags                     1.0.3    1.2.0    1.2.0    Normal       ---
inotify->futures                      0.1.21   0.1.29   0.1.29   Normal       ---
inotify->inotify-sys                  0.1.2    0.1.3    0.1.3    Normal       ---
inotify->libc                         0.2.59   0.2.62   0.2.62   Normal       ---
inotify-sys->libc                     0.2.59   0.2.62   0.2.62   Normal       ---
kernel32-sys->winapi                  0.2.8    Removed  Removed  Normal       ---
kernel32-sys->winapi-build            0.1.1    Removed  Removed  Build        ---
lazy_static                           1.3.0    1.4.0    1.4.0    Normal       ---
libdbus-sys->pkg-config               0.3.11   0.3.16   0.3.16   Build        ---
libpulse-binding                      2.5.0    2.13.0   2.13.0   Normal       ---
libpulse-binding->libc                0.2.59   0.2.62   0.2.62   Normal       ---
libpulse-binding->libpulse-sys        1.5.0    1.11.0   1.11.0   Normal       ---
libpulse-sys->libc                    0.2.59   0.2.62   0.2.62   Normal       ---
libpulse-sys->pkg-config              0.3.11   0.3.16   0.3.16   Build        cfg(target_os = "linux")
log->cfg-if                           0.1.3    0.1.10   Removed  Normal       ---
log->log                              0.4.1    0.4.8    Removed  Normal       ---
maildir                               0.1.1    0.1.2    0.1.2    Normal       ---
maildir->mailparse                    0.5.1    0.6.5    0.6.5    Normal       ---
mailparse->base64                     0.1.1    0.9.3    0.9.3    Normal       ---
mailparse->quoted_printable           0.3.3    0.4.1    0.4.1    Normal       ---
memchr->libc                          0.2.59   Removed  Removed  Normal       ---
nix                                   0.14.1   ---      0.15.0   Normal       ---
nix->bitflags                         1.0.3    1.2.0    1.2.0    Normal       ---
nix->cc                               1.0.15   1.0.45   1.0.45   Build        cfg(target_os = "dragonfly")
nix->cfg-if                           0.1.3    0.1.10   0.1.10   Normal       ---
nix->libc                             0.2.59   0.2.62   0.2.62   Normal       ---
notmuch                               0.1.1    ---      0.5.0    Normal       ---
notmuch->libc                         0.2.59   0.2.62   0.2.62   Normal       ---
num                                   0.1.42   ---      0.2.0    Normal       ---
num->num-bigint                       0.1.43   0.1.44   0.2.3    Normal       ---
num->num-complex                      0.1.43   ---      0.2.3    Normal       ---
num->num-integer                      0.1.36   0.1.41   0.1.41   Normal       ---
num->num-iter                         0.1.35   0.1.39   0.1.39   Normal       ---
num->num-rational                     0.1.42   ---      0.2.2    Normal       ---
num->num-traits                       0.2.3    0.2.8    0.2.8    Normal       ---
num-bigint->num-integer               0.1.36   0.1.41   0.1.41   Normal       ---
num-bigint->num-traits                0.2.3    0.2.8    0.2.8    Normal       ---
num-bigint->rand                      0.4.2    0.4.6    Removed  Normal       ---
num-bigint->rustc-serialize           0.3.24   ---      Removed  Normal       ---
num-complex->num-traits               0.2.3    0.2.8    0.2.8    Normal       ---
num-complex->rustc-serialize          0.3.24   ---      Removed  Normal       ---
num-integer->num-traits               0.2.3    0.2.8    0.2.8    Normal       ---
num-iter->num-integer                 0.1.36   0.1.41   0.1.41   Normal       ---
num-iter->num-traits                  0.2.3    0.2.8    0.2.8    Normal       ---
num-rational->num-bigint              0.1.43   0.1.44   0.2.3    Normal       ---
num-rational->num-integer             0.1.36   0.1.41   0.1.41   Normal       ---
num-rational->num-traits              0.2.3    0.2.8    0.2.8    Normal       ---
num-rational->rustc-serialize         0.3.24   ---      Removed  Normal       ---
parse-zoneinfo->regex                 0.2.11   ---      1.3.1    Normal       ---
proc-macro2->unicode-xid              0.1.0    0.2.0    0.2.0    Normal       ---
progress->terminal_size               0.1.7    0.1.8    0.1.8    Normal       ---
quote->proc-macro2                    0.3.8    1.0.4    1.0.4    Normal       ---
rand->fuchsia-zircon                  0.3.3    Removed  Removed  Normal       cfg(target_os = "fuchsia")
rand->libc                            0.2.59   0.2.62   0.2.62   Normal       cfg(unix)
rand->libc                            0.2.59   0.2.62   Removed  Normal       cfg(unix)
rand->winapi                          0.3.4    0.3.8    0.3.8    Normal       cfg(windows)
rand->winapi                          0.3.4    0.3.8    Removed  Normal       cfg(windows)
redox_termios->redox_syscall          0.1.37   Removed  Removed  Normal       ---
regex->aho-corasick                   0.6.4    0.6.10   0.7.6    Normal       ---
regex->memchr                         2.0.1    2.2.1    2.2.1    Normal       ---
regex->regex-syntax                   0.5.6    ---      0.6.12   Normal       ---
regex->thread_local                   0.3.5    0.3.6    0.3.6    Normal       ---
regex->utf8-ranges                    1.0.0    1.0.4    Removed  Normal       ---
regex-syntax->ucd-util                0.1.1    0.1.5    Removed  Normal       ---
serde                                 1.0.53   1.0.101  1.0.101  Normal       ---
serde_derive                          1.0.53   1.0.101  1.0.101  Normal       ---
serde_derive->proc-macro2             0.3.8    1.0.4    1.0.4    Normal       ---
serde_derive->quote                   0.5.2    1.0.2    1.0.2    Normal       ---
serde_derive->syn                     0.13.7   1.0.5    1.0.5    Normal       ---
serde_json                            1.0.17   1.0.40   1.0.40   Normal       ---
serde_json->dtoa                      0.4.2    Removed  Removed  Normal       ---
serde_json->itoa                      0.4.1    0.4.4    0.4.4    Normal       ---
serde_json->serde                     1.0.53   1.0.101  1.0.101  Normal       ---
syn->proc-macro2                      0.3.8    1.0.4    1.0.4    Normal       ---
syn->quote                            0.5.2    1.0.2    1.0.2    Normal       ---
syn->unicode-xid                      0.1.0    0.2.0    0.2.0    Normal       ---
terminal_size->kernel32-sys           0.2.2    Removed  Removed  Normal       ---
terminal_size->libc                   0.2.59   0.2.62   0.2.62   Normal       ---
terminal_size->winapi                 0.2.8    0.3.8    0.3.8    Normal       ---
termion->libc                         0.2.59   Removed  Removed  Normal       cfg(not(target_os = "redox"))
termion->redox_syscall                0.1.37   Removed  Removed  Normal       cfg(target_os = "redox")
termion->redox_termios                0.1.1    Removed  Removed  Normal       cfg(target_os = "redox")
textwrap->unicode-width               0.1.4    0.1.6    0.1.6    Normal       ---
thread_local->lazy_static             1.3.0    1.4.0    1.4.0    Normal       ---
thread_local->unreachable             1.0.0    Removed  Removed  Normal       ---
time->libc                            0.2.59   0.2.62   0.2.62   Normal       ---
time->redox_syscall                   0.1.37   0.1.56   0.1.56   Normal       cfg(target_os = "redox")
time->winapi                          0.3.4    0.3.8    0.3.8    Development  ---
toml                                  0.4.6    0.4.10   0.5.3    Normal       ---
toml->serde                           1.0.53   1.0.101  1.0.101  Normal       ---
unreachable->void                     1.0.2    Removed  Removed  Normal       ---
uuid                                  0.6.3    0.6.5    0.7.4    Normal       ---
uuid->cfg-if                          0.1.3    0.1.10   Removed  Normal       ---
uuid->rand                            0.4.2    0.4.6    0.6.5    Normal       ---
winapi->winapi-i686-pc-windows-gnu    0.4.0    ---      Removed  Normal       i686-pc-windows-gnu
winapi->winapi-x86_64-pc-windows-gnu  0.4.0    ---      Removed  Normal       x86_64-pc-windows-gnu
```

After:
```Bash
$ cargo outdated
All dependencies are up to date, yay!
```

### CODE REVIEW

**Comment by ammgws** [comment]
Refer to #272

**Comment by atheriel** [comment]
To echo @ammgws, we don't generally merge PRs that blanket update dependencies. Is there a reason you had in mind for some of these updates?

**Comment by michelboaventura** [comment]
I should've found #272 before opening this PR. I really don't have any reason to update this dependencies, I was just playing with the project. Thank you for pointing me out the project's update policy @ammgws and @atheriel. I'm closing this PR then. Cheers.

**Comment by atheriel** [comment]
No worries, I'm happy to see your enthusiasm. I've just added a `CONTRIBUTING` document with a section on this topic, which should hopefully be more visible to potential contributors than the existing discussion issue.

**Pull request closed without merging**
