### PR TITLE
focused_window block: allow show_marks to hide underscored marks

### PR DESCRIPTION
**Pull request by ammgws**
@travankor this should complete your feature request

### CODE REVIEW

**Comment by travankor** [comment]
Seems like everything is working 👍

**Comment by travankor** [comment]
@ammgws not sure if this is related or entirely separate, but seems like Xwayland windows causes  this block to freeze

**Comment by ammgws** [comment]
Interesting, is that regardless of whether show_marks is set?

**Comment by travankor** [comment]
seems like it is regardless of what value you have for `show_marks`

**Pull request merged**
