### PR TITLE
formatting: embed icons using ^icon syntax

### LINKED ISSUE #1527: Allow theme overrides to link to existing colors
For example in `kdeconnect` block could then do:

```toml
[[block]]
block = "kdeconnect"
format = "$bat_charge $connected{OK}|^phone_disconnected"
```
Where `phone_disconnected` is an icon from the icon file, and `^` is just example syntax for specifying icons

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Resolves #1527

Will work nicely with #1618

Not documented yet. See `net` and `speedtest` for examples.

### CODE REVIEW

**Comment by ammgws** [comment]
Do you think `$icon_<iconname>`instead of `^<iconname>` would be more readable?

**Comment by MaxVerevkin** [comment]
> Do you think `$icon_<iconname>`instead of `^<iconname>` would be more readable?

Hmm, maybe. But then it would look like a variable... And as if it could be formatted with some formatter, which it can't. But yeah, `^` seems kinda arbitrary.

**Comment by ammgws** [comment]
> it would look like a variable... And as if it could be formatted with some formatter,

Hmm I guess `^icon_<iconname>` could work then, just seems better to have the prefix for readability.

**Comment by arathunku** [comment]
While working on https://github.com/greshake/i3status-rust/pull/1618 I was actually wondering if it would be possible to have something like `" $icon.music " ` or `" $icon.set("music") "` (this one is annoying because double `"` quotes) but it would change the meaning of `$` and require special casing this in template.rs :sob: 

Going with `^`/`^icon` is really clever. :clap: 

In Elixir there's thing called [sigils](https://elixir-lang.org/getting-started/sigils.html), maybe this could be better for feature extension? `~i()` for icon

**Comment by MaxVerevkin** [comment]
> Hmm I guess `^icon_<iconname>` could work then, just seems better to have the prefix for readability.

Done.

> `~i()` for icon

I think for someone who've never seen it, this is just as cryptic as `^<icon>`...

**Review by ammgws — APPROVED** [review]

**Pull request merged**
