### PR TITLE
themes: Add Gruvbox light and dark

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by polyzen** [comment]
Looks like there are still mistakes. Will fix and squash the commits.

**Comment by polyzen** [comment]
LGTM

**Comment by greshake** [comment]
Thanks for your help :+1: I don't think you have the newest version, I made some changes to themes (added an additional property, alternating tints, just insert #000000 to ignore). Please update your version and adapt to the new changes so I can merge with master :)

**Comment by polyzen** [comment]
Yes, I had noticed that and was going to do so. :)

**Comment by polyzen** [comment]
This feels more readable -- `#ebdbb2` as foreground to colored backgrounds. What do you think?

**Comment by greshake** [comment]
Looks good to me :) Thanks!

**Comment by polyzen** [comment]
I had not committed the changes for the last screenshot. :p

**Pull request merged**
