### PR TITLE
`set_text()`: check whether the content is empty

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Improve #1071 and #1072. Fix issues like #1001 for every block (in theory).

### CODE REVIEW

**Comment by ammgws** [comment]
> @ammgws Maybe do this check inside of TextWigdet on every set_text? Or maybe introduce set_text_checked function? I think that would be more ergonomic.

I think it's better to do it with `set_text`, otherwise someone writing a block might get confused as to which one is meant to be used. However, can we check what happens with blocks that have multiple widgets? e.g. networkmanager block

**Comment by MaxVerevkin** [comment]
NetworkManager works fine for me.

**Comment by ammgws** [comment]
Can you squash your commits?

**Comment by MaxVerevkin** [comment]
I hope I didn't break everything with `get rebase`

**Comment by MaxVerevkin** [comment]
I thought there is an option in github to squash commits while merging.

**Comment by MaxVerevkin** [comment]
Ehhh, I did

**Comment by MaxVerevkin** [comment]
Yay, did it.

**Comment by ammgws** [comment]
Thanks!

**Pull request merged**
