### PR TITLE
Remove chan and add crossbeam_channel

### PR DESCRIPTION
**Pull request by rumpelsepp**
As promised in #360, here is the port to crossbeam_channel. The pull request needs a bit more cleanup.

### CODE REVIEW

**Comment by atheriel** [comment]
Awesome! Thanks for taking this on!

cc @greshake: the concurrency code is mostly your domain, in case you have any comments.

Closes #264.

**Comment by rumpelsepp** [comment]
IMO the code needs a bit more polish. Since I haven't been fully soaked into the codebase I can't assess if it's ready yet. But it builds and seems to work. :)

**Comment by ammgws** [comment]
> This library is an alternative to std::sync::mpsc with more features and better performance.

Perhaps could revisit whether we can use the standard library instead?

**Comment by rumpelsepp** [comment]
> Perhaps could revisit whether we can use the standard library instead?

Valid point. I didn't investigate if the multiple producer, multiple consumer pattern is absolutely required. If not, I might just update to `std` and multiple producer, single consumer instead.

**Comment by atheriel** [comment]
I believe stabilization of `std::Future` is on the horizon, too, so we could possibly adopt that instead.

**Comment by rumpelsepp** [comment]
I tried the `Futures` stuff a year ago and it was so confusing... Maybe once `async`/`await` has settled it might be worth porting. For now I suggest sticking to the synchronous code.

**Comment by greshake** [comment]
Thanks for the PR! 
I want to redo the entire system with async await and/or futures at some point, but it has proven to be a really frustrating experience. My goal is to improve the ergonomics of writing async blocks, but it seems to just grow in complexity. While Futures were stabilized in 1.36 we are still a long way from actually meeting the ergonomic requirements and so we should certainly switch to crossbeam in the meantime. I'll check this out and merge if it works, it should be a seamless transition.

**Comment by greshake** [comment]
I merged the PR manually to add soem corrections for the current version. Most of the crossbeam dependency could also be omitted since we only need crossbeam_channel. 
Cheers :)

**Pull request closed without merging**
