### PR TITLE
Do not fail if the battery is not available (sysfs driver)

### PR DESCRIPTION
**Pull request by flying7eleven**
Hi,

right now I have a Linux installation on a thumb-drive which I use on a laptop as well as a desktop computer. Obviously, the desktop computer does not have a battery which makes using `i3stats-rs` not very feasible. There are several open issues (for example #568 and #85) with a similar problem.

This patch introduces the `allow_unavailable_battery` option for the `battery`-Block (right now just for the sysfs backend) to solve this issue. If this option is set to `true`, a non-existent battery will not raise an error but will instead show a non-available battery icon and text. If the option is set to `false` (which is the default), the behavior is the same as in the current release version.

Unfortunately I do not have an laptop with an removable battery so I cannot test the behavior of the change if the battery is removed during runtime, but I think it should fix this issue as well.

I am still working on the UPower backend but right now I am not sure how to solve it in a adequate way.

Any suggestions or comments? :)

Best,
Tim

### CODE REVIEW

**Comment by PhilipConte** [comment]
I would love for this to work, and especially for the block to not show at all when there's no battery. 

I gave a crack at a slightly different approach

https://github.com/PhilipConte/i3status-rust/commit/cfacf92cff1f305cb877ce5b445da9d5c80b2dcd

but my Rust experience is both very limited and stale, so there's a variety of errors in it.

Hopefully it can inspire you.

**Comment by flying7eleven** [comment]
I just saw that there would be merge issues with the pull request, just fixed them real quick.

@PhilipConte I haven't had time so far to look into your changes but I do so as soon as I have some spare time.

**Comment by ammgws** [comment]
@flying7eleven Personally I am leaning towards merging this, but IIRC there were some differing opinions when these battery related bar failures were brought up in past issues. Could you please summarise the situation from those past issues?

**Comment by flying7eleven** [comment]
Hey @ammgws, yeah, there was a quite long discussion about different approaches and pros and cons. One of the solutions I also would like and prefer was a profile-based options where one could load the blocks based on a profile for the current computer. This would result in a lot of refactoring of the current code-base and would not be a short-term solution. Another solution was - and still is - to use the UPower blocks `DisplayDevice` option (which seems not to work when live-removing a battery) (don't know how my solution would handle that, btw.). The here suggested patch was more and quick (and hopefully not so dirty) solution so I could use `i3status-rs` on my quite weird setup. I could only find one other user with a similar setup who could use it (at least based on use issues) and several others with live-unplugging the battery where I do not know if this would be a solution.

The most controversial discussions were about the fact if the block should be still be displayed or completely hidden if the batteries where not detected. I've gone for the fist solution so it might behave better with live-unplugging.

I hope this helps, if not, let me know!

**Comment by Nukesor** [comment]
Hiding this behind a configuration flag seems like a very sensible thing to do. Would love to see this added to the project.

Feel free to ping me, if you need someone to test this PR.

**Comment by flying7eleven** [comment]
If there is still interest in this pull request, I could bring it to a state where it could be merged into the master in the next few days 👍🏻

**Comment by Nukesor** [comment]
@flying7eleven Hey :)

I just took the opportunity and created a follow-up PR with a few more features and hot-swap support.
Your PR has been the basis, I hope this isn't a problem :)

PR can be found over here: https://github.com/greshake/i3status-rust/pull/835

**Comment by flying7eleven** [comment]
Why should it be a problem, @Nukesor? That's the advantage of open source development. Anything can be used and improved :)

**Comment by flying7eleven** [comment]
Closing this PR in favor of #835

**Pull request closed without merging**
