### PR TITLE
Fix music block only showing icon #204

### LINKED ISSUE #204: Music block only shows music icon
Music block does not display the marquee or play icon with any player when music is playing. I have tried with vlc, mpd, mpc, ncmpcpp and rhythmbox commands but never shown. I'm using i3status-rs with sway.
```
[theme]
name = "slick"
[theme.overrides]
idle_bg = "#303030"
idle_fg = "#C6C6C6"
info_bg = "#A83334"
info_fg = "#C6C6C6"
good_fg = "#C6C6C6"
warning_fg = "#C6C6C6"
critical_fg = "#C6C6C6"
[icons]
name = "awesome"

[[block]]
block = "music"
player = "vlc"
marquee = true
max_width = 20
buttons = ["play"]

[[block]]
block = "disk_space"
path = "/"
alias = "root"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
interval = 3

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%d-%m-%y %R"
```

### PR DESCRIPTION
**Pull request by tablet-mode**
Fixes #204 by using new definition of org_freedesktop_dbus::Properties

### CODE REVIEW

**Comment by tablet-mode** [comment]
@atheriel Exactly, I couldn't find a changelog right now but here is the commit which fixed their own code example: https://github.com/diwic/dbus-rs/commit/e10d050668bc88cc4dc4d718f72a1bc1a0642bc7

**Comment by danieltomasz** [comment]
Hi, I  build i3status from this commit, and player is indeed working.
But displayed play key doesnt switch to pause  key when I pause player 
( the player behvior is ok, clicking button pausing it)

**Comment by tablet-mode** [comment]
Whoopsie, missed that one. Thanks for testing :+1: 

Updated the PR to fix this.

**Comment by atheriel** [comment]
OK, that's good enough for me. Thanks!

**Pull request merged**
