### PR TITLE
chore: Update multiple dependencies

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
This is alternative to #483

**Comment by ignatenkobrain** [comment]
Even though there are some new deps, overall this reduces dependency list by 2 crates :)

**Comment by ammgws** [comment]
Dependency graphs

Before
before

After
after

**Comment by ignatenkobrain** [comment]
@ammgws is that good or bad? Sorry, not very clear to me :)

**Comment by tim77** [comment]
Just want to add my 2 cents: binary size with new deps decreased - 6,7M vs 6,3M. But probable this is not clear comparison  because this is native Fedora binary vs upstream cargo.

**Comment by ignatenkobrain** [comment]
Strictly speaking, depending on compilation options it is different:

```
⋊> ~/t/i3status-rust on master ↑ du -h target{-before,}/release/i3status-rs{,.stripped}                                                                                     18:38:18
45M	target-before/release/i3status-rs
52M	target/release/i3status-rs
5.5M	target-before/release/i3status-rs.stripped
6.2M	target/release/i3status-rs.stripped
```

I have compiled it before and after with `-Ccodegen-units=1 -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now`

**Comment by ammgws** [comment]
@ignatenkobrain just to try visualise the changes and see where the reductions occurred

**Comment by atheriel** [comment]
I believe @ammgws has done quite a lot of related work on updating dependencies to reduce transitive deps, so I'm not sure this is relevant anymore (and would need to be rebased in any case).

**Pull request closed without merging**
