### PR TITLE
battery: read remaining time from time_to_empty_now and time_to_full_now if they exist

### PR DESCRIPTION
**Pull request by Thra11**
Otherwise, fall back to original calculations for time_remaining.

w.r.t. the code, I think the general idea is ok (collect possible sources of information as `Options`/`Result`s, then calculate the time based on the charging status and available info sources), but I suspect the code could be cleaner. There is some potential to optimise by not reading more values once we've found a suitable source, but due to the fact there are two calculations (time to empty vs. time to full) which sometimes use the same values (`fill`, `full` & `usage`) it would add some complexity, or wouldn't handle situations where e.g. `time_to_empty_now` can be read directly but `time_to_full_now` cannot and needs to be calculated.

Also, I'm not sure what this line is supposed to do, so I've basically left it alone. Is there a situation where the status is "Full", but the remaining time (until what?) isn't zero?
```
"Full" => Ok(((full as f64 / usage) * 60.0) as u64),
```

### CODE REVIEW

**Comment by GladOSkar** [comment]
Good point, i have no idea why that line is written that way

**Comment by Thra11** [comment]
Assuming "Full" means the charger is connected but the charge/capacity is at 100%, then the two possible values for the remaining time are 0 (time to full, i.e. it will be full in 0 seconds) or infinity (time to empty, i.e. based on the current state, it will never be empty as it's not discharging). I can't see any benefit to trying to represent infinity, so I suggest we remove the line, and let the `"Full"` state be handled in the `_` bit, which returns 0. The 0 value will be hidden thanks to the other recent PR, so it shouldn't look weird or confusing.

**Comment by GladOSkar** [comment]
Sounds good to me

**Comment by ammgws** [comment]
I was hoping to setup my new laptop in order to test this but not sure when I can get around to it so hopefully some other laptop users could test run this!

**Comment by GladOSkar** [comment]
Just tested, works fine

**Comment by ammgws** [comment]
Out of interest which of the following does your laptop support?

time_to_empty
time_to_full
energy_full
charge_full
energy_now
charge_now
power_now
current_now

**Comment by GladOSkar** [comment]
```
% ls -1 /sys/class/power_supply/BAT0/ 
hwmon0/
power/
alarm
capacity
capacity_level
charge_full
charge_full_design
charge_now
current_now
cycle_count
device -> ../../../PNP0C0A:00
manufacturer
model_name
present
serial_number
status
subsystem -> ../../../../../../class/power_supply
technology
type
uevent
voltage_min_design
voltage_now
```

**Comment by ammgws** [comment]
Thanks!

**Pull request merged**
