### PR TITLE
music block: merge two threads into one

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Also: initialize `Player` struct when a new player is created.

### CODE REVIEW

**Comment by ammgws** [comment]
Glad we can finally combine the two threads.

> solves some issues I've faced (https://github.com/greshake/i3status-rust/issues/1124#issuecomment-803599620)

Which issues does it solve?

Some initial testing with mpv: on play/pause the block is updating twice, presumably because the "updated = true" checks were removed.

**Comment by MaxVerevkin** [comment]
> Which issues does it solve?

Sometimes a new player wouldn't work properly because when the block discovers it, it doesn't query the info and just waits for the properties to be changed.

> presumably because the "updated = true" checks were removed.

Ah yes, will add it.

**Comment by ammgws** [comment]
> Sometimes a new player wouldn't work properly because when the block discovers it, it doesn't query the info and just waits for the properties to be changed.

Ah OK that makes sense.

**Comment by ammgws** [comment]
Thanks, much better!

**Pull request merged**
