### PR TITLE
Implement error handling

### PR DESCRIPTION
**Pull request by pitkley**
(Regarding #42, cc @greshake @jheyens.)

So, this turned out to be a pretty big PR, given that almost everything had to be touched to support the `Result` type and the associated error-handling.

I'll try to summary the biggest changes/additions to maybe ease the burden a bit.

## Summary (by files)

* `src/errors.rs`

    * Added supporting code for error handling. This includes:

        * An `enum Error` containing two types of errors: `BlockError` and `InternalError`
        * A custom `Result` type which allows omitting of our `Error`
        * Two trait extensions (`ResultExt`, `OptionExt`) which add:
        
            ```rust
            fn block_error(self, block: &str, message: &str) -> Result<T>;
            fn internal_error(self, block: &str, message: &str) -> Result<T>;
            ```

            to both `Option` and `Result`, allowing easy error handling.

        * An implementation for `std::fmt::Display` for conversion to string (used in `main.rs` to actually output an error).

* `src/main.rs`

    * Renamed `main` to `run`
    * Added another `main` method which executes `run` and catches errors which might occur directly in `main`.
    * Moved CLI matching to the new `main`
    * Added CLI flag `--exit-on-error` to exit if an error occurs, rather than outputting to i3bar.
    * Replaced every relevant `.unwrap` and `.expect` by `.internal_error` to have full error handling

* `src/block.rs`

    * Updated `trait Block` to include the `Result` type

* `src/blocks/*.rs`

    * Updated all blocks to match changed `trait Block`
    * Replaced every relevant `.unwrap` and `.expect` by `.block_error` to have full error handling

* `README.md`

    * Updated to reflect the new requirements regarding having a `Result` type

* `src/{icons,themes}.rs`

    * Updated to use `Result` type

* `src/scheduler.rs`

   * Updated to use `Result`
   * Implemented `std::fmt::Display` for `Task` to allow for additional error printing.

* `src/util.rs`

   * Updated to use `Result`

* `src/widgets/*.rs`

   * Updated to use `Result`

## Open tasks, points for discussion

* [x]  Currently both error-types, internal and block, get handled the same way: output to i3bar, then idle until the process gets killed.

    We should determine if we want to handle internal errors differently in anyway to block errors. If not, I'd still vote to keep the distinction between the two for future-proofing, in case we ever want to be able to differentiate between an error that has occured in a block and one that didn't.

    ~~**Note:** Right now the causing error is not retained, for neither internal nor block errors. I would like to implement this to keep the cause for extended debug information, but I am currently at a bit of a roadblock.~~

* [x]  I have not implemented a click-handler yet to allow automatic exporting/posting/... of an error that has occured.

    I think we should first decide on what exactly we want to do, such that it is not too complicated for both the user and the implementation.

### CODE REVIEW

**Comment by pitkley** [comment]
(Oh yeah, besides the two mentioned discussion points, I'd like to wait for #41 to be merged so I can rebase this on the configuration struct rather than the other way around.)

**Comment by svmnotn** [comment]
@pitkley Anything going on here? To address the points:

> We should determine if we want to handle internal errors differently in anyway to block errors. If not, I'd still vote to keep the distinction between the two for future-proofing, in case we ever want to be able to differentiate between an error that has occured in a block and one that didn't.

Well, internal errors should be fairly rare considering that most of the code that does things is in the blocks, so we could just display internal errors with a message saying to check for an open issue or make one? While block errors could potentially be missing a program or something else on the user's end.

> I think we should first decide on what exactly we want to do, such that it is not too complicated for both the user and the implementation.

I think other than the previous point, the exporting should be simplest if we just write whatever we would send out to stderr to a file in some place (Maybe a config option, or maybe just `/tmp/`). Once the user has clicked on the error like @jheyens suggested.

**Comment by pitkley** [comment]
> Well, internal errors should be fairly rare considering that most of the code that does things is in the blocks [...]

Good point. What would have to be changed though is that right now configuration errors are classified as internal errors too, and we wouldn't want a user to open an issue for a wrong configuration as an internal error.

> I think other than the previous point, the exporting should be simplest if we just write whatever we would send out to stderr to a file in some place (Maybe a config option, or maybe just `/tmp/`). Once the user has clicked on the error like @jheyens suggested.

What I thought of that might make it relatively easy for the end-users to open an issue is to implement a click-handler, which will try to `xdg-open` to the issue tracker with the title and body prepopulated:

* https://github.com/greshake/i3status-rust/issues/new?title=Internal%20error:%20yada&body=Log%20of%20internal%20error

If the call to `xdg-open` fails (either because it doesn't exist or exited with a non-zero exit code) we could fall back to a different method.

Implementing a click-handler without the need to create a full-fledged block would require something like #5 though.

Overall, I would suggest to split this second point (supporting the user to report an error) into a separate PR. This would mean merging this PR to lay the groundwork, with the error-reporting right now being a single, non-interactive block telling the user what happened. Cc @greshake, what do you think?

**Comment by pitkley** [comment]
Small update: I added the `ConfigurationError` I mentioned in my [last comment](https://github.com/greshake/i3status-rust/pull/46#issuecomment-309101839). This PR should be okay to merge after review, if the split I mentioned is okay with everybody.

**Comment by greshake** [comment]
I'll merge this now. I will add backtraces and a couple other improvements when it's on master. As always great work :+1:

**Pull request merged**
