### PR TITLE
music: fix spacing

### PR DESCRIPTION
**Pull request by MaxVerevkin**
### Before
image
### After
image

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Set spacing to `Hidden` because icons already contain spaces.

**Comment by ammgws** [comment]
Can you show me what it looks like with all the buttons showing? Prev, play and next

**Comment by MaxVerevkin** [comment]
### Before
image
### After
image

**Comment by ammgws** [comment]
What's the actual JSON output? Would be easier to tell that way.

**Comment by MaxVerevkin** [comment]
### Before
```
{"background":"#2196f3","color":"#ffffff","full_text":"   ","markup":"pango","name":"18446744073709551614","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#ffffff","full_text":"   ","markup":"pango","name":"18446744073709551615","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#ffffff","full_text":"   ","markup":"pango","name":"18446744073709551613","separator":false,"separator_block_width":0}
```
### After
```
{"background":"#2196f3","color":"#ffffff","full_text":"  ","markup":"pango","name":"18446744073709551614","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#ffffff","full_text":"  ","markup":"pango","name":"18446744073709551615","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#ffffff","full_text":"  ","markup":"pango","name":"18446744073709551613","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#535353FF","full_text":"","markup":"pango","separator":false,"separator_block_width":0}
```

**Comment by ammgws** [comment]
Ah OK so we still get the double spaces between the buttons

**Comment by MaxVerevkin** [comment]
Yeah, with the current icons system it is not possible to have just one space between icons.

**Comment by ammgws** [comment]
We could loop over the widgets and set the spacing appropriately that way (trimming the spaces around the icon first).

**Comment by MaxVerevkin** [comment]
To be honest I don't see that much of a problem in this. At least it is well-defined what happens if I click between the icons when we have two spaces around them.

**Comment by MaxVerevkin** [comment]
@ammgws Do you know the story behind having spaces around all the icons?

**Comment by ammgws** [comment]
The spacing between the music block icons has come up at least one before: https://github.com/greshake/i3status-rust/issues/468
So it is likely to come up again. However I guess you can work around it by implementing this PR and then having the user to manually override the icons?

and yes the icons were like that from the beginning. If every block had a format string from the start then it would have been much simpler.

**Comment by ammgws** [comment]
Test config (icon text changes to make comparison more visible) with the same spaces around the icons as they have now:
```toml
[icons]
name = "none"
[icons.overrides]
music = " XX "
music_prev = " prev "
music_play = " play "
music_next = " next "

[[block]]
block = "music"
buttons = ["play", "prev", "next"]
```

Before this PR:
```
"full_text":"■XX■Billie Jean - Michael Jac■"
"full_text":"■prev■■"
"full_text":"■play■■"
"full_text":"■next■■"
```
On one line: `■XX■Billie Jean - Michael Jac■■prev■■■play/pause■■■next■■`

After this PR:
```
"full_text":"■XX■Billie Jean - Michael Jac"
"full_text":"■prev■"
"full_text":"■play■"
"full_text":"■next■"
```
On one line: `■XX■Billie Jean - Michael Jac■prev■■play■■next■`

-------------------

Test config with the spaces around the icons removed:
```toml
[icons]
name = "none"
[icons.overrides]
music = " XX "
music_prev = "prev"
music_play = "play"
music_next = "next"

[[block]]
block = "music"
buttons = ["play", "prev", "next"]
```

Before this PR:
```
"full_text":"■XX■Billie Jean - Michael Jac■"
"full_text":"prev■"
"full_text":"play■"
"full_text":"next■"
```
On one line: `■XX■Billie Jean - Michael Jac■prev■play■next■`

After this PR:
```
"full_text":"■XX■Billie Jean - Michael Jac"
"full_text":"prev"
"full_text":"play"
"full_text":"next"
```
On one line: `■XX■Billie Jean - Michael Jacprevplaynext`

--------

# Conclusion

Before this PR, even if you overrode the icons in your config you could not get rid of all the spaces.
After this PR you can customise it all the way down to 0 spaces, so I would call that an improvement.

**Comment by ammgws** [comment]
Thanks!

**Pull request merged**
