### PR TITLE
Block update changed to right click

### PR DESCRIPTION
**Pull request by ram02z**
Initially, I just wanted to change the apt block to use right click to update instead of left because left click is used for the `on_click` property. However, I realised there are a few blocks that also have some sort of update function when left click is clicked, so I updated them accordingly.

In a nutshell, I just wanted to be able to have an extra bind (left click), whilst retaining the block's existing update functionality. This is particularly useful for blocks that tend to have long intervals like the apt block.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
I don't believe that's the right thing to do.

> > and give it some special syntax so you can choose to force update the block instead of running a custom command
> 
> IMO, every block should always update when clicked, even if `on_click` is set.

Would something like that work for you (from #1036)?

**Comment by ram02z** [comment]
> I don't believe that's the right thing to do.
> 
> > > and give it some special syntax so you can choose to force update the block instead of running a custom command
> > 
> > IMO, every block should always update when clicked, even if `on_click` is set.
> 
> Would something like that work for you (from #1036)?

Yeah, that's probably a better method because I just want to retain the update functionality of some blocks.

**Comment by MaxVerevkin** [comment]
@ammgws what do you think?

**Comment by ammgws** [comment]
> @MaxVerevkin: IMO, every block should always update when clicked, even if on_click is set.

That is what [py3status](https://py3status.readthedocs.io/en/latest/configuration.html#custom-click-events) (and possibly other ones) does so it may be the right way to go: "As an added feature and in order to get your i3bar more responsive, every on_click command will also trigger a module refresh". However, do you think we would need to allow that behaviour to be disabled as well? For example if you have set a custom `on_click` command for the Pacman block that pops up the list of pending updates, but you don't want it to trigger the block update function when you click on it.

**Comment by ram02z** [comment]
> For example if you have set a custom `on_click` command for the Pacman block that pops up the list of pending updates, but you don't want it to trigger the block update function when you click on it.

Speaking of list of pending updates, how would you go about getting the list of pending updates from apt's temporary package database? Currently I have to run `sudo apt update && apt list --upgradable` which takes a while to update.

**Comment by MaxVerevkin** [comment]
> However, do you think we would need to allow that behaviour to be disabled as well?

```toml
[[block]]
block = "pacman"
on_click = "..."
update_on_click = false # defaults to true
```

**Comment by ammgws** [comment]
> @ram02z: Speaking of list of pending updates, how would you go about getting the list of pending updates from apt's temporary package database? Currently I have to run `sudo apt update && apt list --upgradable` which takes a while to update.

I will see if i I can look into it (not my daily driver so will need to grab another machine)

**Comment by ram02z** [comment]
> @ram02z, this should do it: `APT_CONFIG=/tmp/i3rs-apt/apt.conf apt list --upgradable`

Thank you!

**Comment by ammgws** [comment]
I'll add it to the block documentation. If you come up with an `on_click` command that pops up a menu with the list of updates or something, please open a PR to add the example to the docs :+1:

**Comment by ram02z** [comment]
> I'll add it to the block documentation. If you come up with an `on_click` command that pops up a menu with the list of updates or something, please open a PR to add the example to the docs +1

Sure! I currently use [i3-quickterm](https://github.com/lbonn/i3-quickterm) in order to show a popup terminal with the updates.

**Comment by MaxVerevkin** [comment]
> > However, do you think we would need to allow that behaviour to be disabled as well?
> 
> ```toml
> [[block]]
> block = "pacman"
> on_click = "..."
> update_on_click = false # defaults to true
> ```

Or perhaps something like that? (not sure if this is a valid toml)

```toml
[[block]]
block = "pacman"
[[block.click]]
button = "left"
cmd = "..."
update = false # defaults to true
[[block.click]]
button = "right"
cmd = "..."
```

**Comment by ram02z** [comment]
> I'll add it to the block documentation. If you come up with an `on_click` command that pops up a menu with the list of updates or something, please open a PR to add the example to the docs +1

Created the example for apt PR.

Also I think a separate PR should be created about the ideas discussed here, since this PR is really just a quickfix.

**Pull request closed without merging**
