### PR TITLE
weather(metno): weathericon API was terminated, use pre-fetched data

### LINKED ISSUE #1939: weather(metno) "Legend replied in unknown format"
Today, after getting back from a vacation, my amd_gpu block is trowing an error in red "Legend replied in unknown format".
My config (amd part):

```
block = "amd_gpu"
device = "card1"
format = " $icon $utilization $vram_used_percents ($vram_used/$vram_total)"
interval = 10
[block.theme_overrides]
idle_bg = "#778BB7af"
idle_fg = "#ffffffda"
```

My system: 
Linux ngc-ryzen7 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux

 #~  inxi -G
```
Graphics:
  Device-1: AMD Navi 31 [Radeon RX 7900 XT/7900 XTX] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.8 driver: X: loaded: amdgpu
    unloaded: modesetting dri: radeonsi gpu: amdgpu resolution:
    1: 2560x1440~144Hz 2: 1080x1920~60Hz
  API: OpenGL v: 4.6 Mesa 23.1.6-arch1.4 renderer: AMD Radeon RX 7900 XT
    (gfx1100 LLVM 16.0.6 DRM 3.52 6.4.12-arch1-1)
```

I do not know what could be changed to be honest, since it was trowing the error, before updating via pacman. Anyways, an update didn't help - there were no updates concerning the video subsystem or i3status-rs.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Fixes #1939

### CODE REVIEW

**Review by bim9262 — APPROVED** [review]
lgtm!

**Comment by bim9262** [comment]
We may want to note that as of August 31, 2023 all older versions of i3-status will be unable to use weather from metno

**Comment by MaxVerevkin** [comment]
> We may want to note that as of August 31, 2023 all older versions of i3-status will be unable to use weather from metno

In the docs or release notes?

**Comment by bim9262** [comment]
I'd just add that to the release notes. If someone notices that it doesn't work on their system they'll probably look at issues, pull requests, and the change log before going to the docs.

**Pull request merged**
