### PR TITLE
Enable allow_missing for the UPower driver

### PR DESCRIPTION
**Pull request by bim9262**
Added additonal match filters in the monitor function to let us know
when a upower devices is added or removed.

Implimented the is_availible function for UpowerDevice.

Deduplicated logic in Battery's update function regarding the return
values.

Updated blocks.md to remove note about allow_missing not working for
drivers other than the sysfs driver.

### CODE REVIEW

**Comment by bim9262** [comment]
Updated comment in battery.rs regarding allow_missing only working on sysfs devices.

**Comment by bim9262** [comment]
Rebased as there would otherwise be a merge conflict.

**Comment by ammgws** [comment]
In theory this should be ok

**Comment by ammgws** [comment]
Can you resolve the conflicts?

**Comment by bim9262** [comment]
Yes, will do.

**Comment by ammgws** [comment]
Thanks!

**Comment by ammgws** [comment]
This still fails on startup if the device isn't available at that time, so we will need some additional logic for that case..

**Comment by MaxVerevkin** [comment]
I don't have any removable batteries, so I can't check myself, but what's wrong with the `IsPresent` property? Does it even work?

**Comment by bim9262** [comment]
@MaxVerevkin , I don't have any device that will show `IsPresent` when it's present and false when it's not. I have a computer with two different removable batteries (separate bays). When the batteries are removed they simply aren't listed by UPower. Maybe we need to find somebody with an "expensive UPS" (see: https://upower.freedesktop.org/docs/Device.html#Device:IsPresent)

**Pull request merged**
