### PR TITLE
Add `hide_missing` option for Network devices

### LINKED ISSUE #121: Treat missing network device as down
Currently, the network block does not play very nicely with removable network devices.

For example, I have a USB Ethernet adapter and the associated device (in `/sys/class/net`) is only present if the adapter is plugged in.  When the adapter is not there, I get an error instead.

Do you think `hide_inactive` should treat absent devices as being inactive too?  Or perhaps a new `ignore_missing` flag should be added for this?

### LINKED ISSUE #131: On_click option should be available for all blocks
This is just kinda obviously an issue, but I was here to report another bug so i figured i might as well add it to the issues checklist.

### PR DESCRIPTION
**Pull request by JP-Ellis**
If `hide_missing` is `false` (the default), the network symbol is shown with an
'×'.

If `hide_missing` is `true`, the network block is completely omitted.

Closes #121

### CODE REVIEW

**Comment by atheriel** [comment]
The Travis build appears to be failing for a legitimate reason. Are you able to replace your usage of the deprecated interface?

**Comment by JP-Ellis** [comment]
@atheriel This has been fixed in #342 (which has been merged after I created this pull request).  I can rebase if you wish, or leave it as is.

**Comment by atheriel** [comment]
Yes, my mistake. I edited my comment to address the error almost immediately, but not fast enough I see.

**Comment by JP-Ellis** [comment]
I've rebased the commit on top of the `master` so that the tests can pass.

Is there anything more you would like from this pull request before it is merged?

**Comment by atheriel** [comment]
Nope, just did some local testing. Looks good. Thanks for following through with this. :+1:

**Comment by GladOSkar** [comment]
@atheriel @JP-Ellis One thing i noticed: This messes up alternating color schemes because the block is just invisible, not removed.

image

**Comment by JP-Ellis** [comment]
I don't use an alternating color scheme, so didn't notice that.  @GladOSkar, perhaps you should open a new issue so this can be tracked?

**Comment by GladOSkar** [comment]
@JP-Ellis Done #349

**Pull request merged**
