### PR TITLE
Remove trailing comma

### LINKED ISSUE #1089: Latest `master` produces JSON error
`rustc` says:
```
rustc 1.52.0-nightly (a15f484b9 2021-02-22)
```

`i3bar` says:
image

`i3status-rs` says:
```
% i3status-rs ~/.config/i3/status-rs-config.toml 
{"version": 1, "click_events": true}
[[{"full_text":"  Tue 2021-02-23 12:13 ","name":"0","instance":"0","markup":"pango",}],
```

Note the trailing comma in the object. That's not allowed in JSON.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Closes #1089

### CODE REVIEW

**Comment by ammgws** [comment]
Thanks!

**Comment by GladOSkar** [comment]
Actually i think this might have removed the last character of some blocks? My `memory`, `volume` and `battery` blocks are now missing the last character. The `%` sign in the former 2 and the `)` in the last one.

**Comment by MaxVerevkin** [comment]
Yeah, I see. But I think that was introduced in #1076. The issue is that in format string like `some_text {variable} text`, ` text` is dropped. This shouldn't be hard to fix.

**Comment by GladOSkar** [comment]
Yeah i just saw the same thing, hence the deleted comment, sorry. I'll open another issue

**Pull request merged**
