### PR TITLE
Simplify `FormatTemplate`

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Current implementation of formatting is somewhat messy. This is my attempt to rewrite it.

This implementation does not use recursive functions and the data structure is just a vector instead of custom linked list.

Probably needs some testing.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
I'm also thinking of ways to implement "lazy formatting" - the value is computed only if it is present in the format string. Net block would benefint from this feature a lot. Actually, net block already does this in a hachy way: is simply checks if some options are presented using `.contains()`.

Unfortunately, [`std::lazy`](https://doc.rust-lang.org/std/lazy/index.html) is nightly olny.

I tried writing something like:
```rust
pub struct LazyString {
    inner: Option<Box<dyn FnOnce() -> String>>,
    value: Option<String>,
}
impl LazyString {
    pub fn new(x: Box<dyn FnOnce() -> String>) -> Self {
        Self {
            inner: Some(Box::new(x)),
            value: None,
        }
    }
    pub fn init(&mut self) {
        if let Some(inner) = self.inner.take() {
            self.value = Some(inner());
        }
    }
    pub fn val(&self) -> Option<String> {
        self.value.clone()
    }
}

...

    pub fn render_lazy(&self, vars: &mut HashMap<&str, LazyString>) -> Result<String> {
        let mut rendered = String::new();

        for token in &self.tokens {
            match token {
                FormatToken::Text(text) => rendered.push_str(&text),
                FormatToken::Var(ref key) => {
                    let s = vars.get_mut(&**key).unwrap();
                    s.init();
                    rendered.push_str(&format!("{}", s.val().unwrap()));
                }
            }
        }

        Ok(rendered)
    }

```

And it works for simple things like
```rust
        let layout = move || layout;
        let variant = move || variant;

        let mut values = map!(
            "{layout}" => crate::util::LazyString::new(Box::new(layout)),
            "{variant}" => crate::util::LazyString::new(Box::new(variant))
        );

        self.output.set_text(self.format.render_lazy(&mut values)?);

```

But I cannot do stuff like
```rust
        let layout = || self.layout();
        let variant = move || variant;

        let mut values = map!(
            "{layout}" => crate::util::LazyString::new(Box::new(layout)),
            "{variant}" => crate::util::LazyString::new(Box::new(variant))
        );

        self.output.set_text(self.format.render_lazy(&mut values)?);
```

Can someone with more rust experience give me some hints please? Compiler tells me that in this case `self` has to have `static` lifetime.

**Comment by MaxVerevkin** [comment]
Although I don't quite know how exactly integrate it into net block because, for example, it updates ssid only once every 30 seconds.

**Comment by ammgws** [comment]
Can you include the full keyboard_layout example? Might as well commit it.

**Comment by MaxVerevkin** [comment]
@ammgws Done.

**Comment by ammgws** [comment]
Okay, perhaps I'm missing something but couldn't you handle the net block issue you mentioned above by moving the below logic inside the function that returns the SSID?

```rs
let now = Instant::now();
if (now.duration_since(self.last_update).as_secs() > 30)
...
```

**Comment by MaxVerevkin** [comment]
Hmm, well, yes. Why haven't I thought about that :laughing:?

**Comment by MaxVerevkin** [comment]
Ohhh, `self` has to be mutable, that's why I cannot move it there.

> `self.last_update = now;`

**Comment by MaxVerevkin** [comment]
I think I'll wait better wait for [`std::lazy`](https://doc.rust-lang.org/std/lazy/index.html) to be stabilized.

**Comment by MaxVerevkin** [comment]
By the way, I haven't experienced any issues with this implementation yet.

**Comment by ammgws** [comment]
> By the way, I haven't experienced any issues with this implementation yet.

Neither, though just with my personal config. I think it's time for this to get more action via master.

**Comment by ammgws** [comment]
Thanks!

**Comment by MaxVerevkin** [comment]
TODO: Fix the issue with trailing text in format string.

**Pull request merged**
