### PR TITLE
Add support for multiple batteries

### PR DESCRIPTION
**Pull request by mattclement**
I use a Thinkpad with a removable battery, and made this to combine the stats into one. I've been running this successfully for a week now. I'm very new to rust, so if I did things incorrectly please let me know since I'd like to learn.

### CODE REVIEW

**Comment by GladOSkar** [comment]
Related: #220

**Comment by GladOSkar** [comment]
The config syntax makes sense to me, but i can't test it. @droslean could you test it?

Also a `merge = [true/false]` option would be great if it fits into this PR

**Comment by GladOSkar** [comment]
That is a good question actually, i didn't think about that.

If we had 2 Battery blocks that would not be very nice since i think the estimated remaining time should always be merged. Having 2 remaining times does not sound useful at all.

But having Labels may be useful since every usecase i have for wanting the blocks to be separate is to know the state of a specific device (BT Mouse, UPS, etc.)

I think having configurable labels (while it may be a little feature-creepy) is the way to go. Maybe we could use `/sys/class/power_supply/BAT0/model_name` as a default?

**Comment by droslean** [comment]
@GladOSkar  I've tested it. It seems that its working fine.

**Comment by atheriel** [comment]
Thanks for your patience. I have a few comments here, although I am supportive of this feature.

First, what's the interaction between multiple devices and Upower? Or do we only support polling `sysfs` when you have multiple devices? I'd very much like to get Upower support, since it gives such a huge performance gain for this particular block.

Secondly, I'm somewhat unhappy with the `devices` configuration field, because I think it's a workaround we might not really need. I have an inkling that we can write some custom `serde` code to consume strings as a one-element vector, which would mean that we could just use the existing `device` and handle it differently for single vs. multiple batteries. However, writing `serde` code is extremely beginner-unfriendly in my experience, so I can't ask that you do this yourself. I will have to look into it when I have time. (For anyone who's particularly adventurous, you can see our existing `serde` deserialization hacks [here](https://github.com/greshake/i3status-rust/blob/master/src/de.rs)).

Finally, some comments with respect to @GladOSkar's comments on formatting. I'm not sure I really agree that you'd always want the time remaining to be merged -- it's certainly relevant information that one of your batteries is close to empty. Moreover, I'm quite sure that time remaining estimates we make via `sysfs` for a battery that is not discharging will be highly inaccurate, so combining multiple time estimates would actually give you a pretty meaningless result. It's possible that combining estimates from Upower would be more accurate, but I'd like to see some investigation along those lines as well. What do those with multiple batteries see in terms of time estimates when they have two blocks at the moment? How does it look with `sysfs` vs. Upower?

**Comment by atheriel** [comment]
@mattclement Sorry to necro this thread, but is it possible that the support for Upower's `DisplayDevice` in #356 can supersede this PR? Or is there additional functionality here that I'm missing?

**Comment by mattclement** [comment]
@atheriel I think that support does the same thing, yeah.

**Pull request closed without merging**
