### PR TITLE
Fix artist parsing from metadata

### LINKED ISSUE #441: music block blank on fedora 30 with mpd and mpDris2
I can see useful traffic via dbus-monitor in session bus, e.g.

```
method call time=1568269972.557250 sender=:1.14285 -> destination=org.mpris.MediaPlayer2.mpd serial=318 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.mpris.MediaPlayer2.Player"
   string "PlaybackStatus"
method return time=1568269972.559454 sender=:1.3 -> destination=:1.14285 serial=228159 reply_serial=318
   variant       string "Playing"
```

But unfortunately the music block is blank, it only displays the music icon.

Any Idea on what's wrong?

This is on `0.10.0` as well as on master as of today (2019-09-12: f90bc9874d060a24276c2808275f4068d30ba47b).

### PR DESCRIPTION
**Pull request by Riey**
It works in my machine(arch linux + mpd + mpDris2)

Edit: Closes #441.

### CODE REVIEW

**Comment by atheriel** [comment]
To clarify: you think this will fix #441?

This might require a bit more testing against other working setups before I believe it's safe to merge.

**Comment by Riey** [comment]
Yes I had same issue and have debugged music block
then notice extracting artist has problem(other code works good)

so I change this code and work good for me

**Comment by Riey** [comment]
And this is my `dbus-monitor` info

```
method call time=1581354145.353792 sender=:1.395 -> destination=org.mpris.MediaPlayer2.mpd serial=5 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.mpris.MediaPlayer2.Player"
   string "Metadata"
method return time=1581354145.354010 sender=:1.5 -> destination=:1.395 serial=10219 reply_serial=5
   variant       array [
         dict entry(
            string "xesam:album"
            variant                string "Poppin'on!"
         )
         dict entry(
            string "xesam:title"
            variant                string "夢みるSunflower"
         )
         dict entry(
            string "mpris:trackid"
            variant                object path "/org/mpris/MediaPlayer2/Track/126"
         )
         dict entry(
            string "mpris:length"
            variant                int64 281000000
         )
         dict entry(
            string "xesam:contentCreated"
            variant                string "2019"
         )
         dict entry(
            string "xesam:trackNumber"
            variant                int32 9
         )
         dict entry(
            string "xesam:discNumber"
            variant                int32 1
         )
         dict entry(
            string "xesam:artist"
            variant                array [
                  string "Poppin'Party (戸山香澄、花園たえ、牛込りみ、山吹沙綾、市ヶ谷有咲)"
               ]
         )
         dict entry(
            string "xesam:url"
            variant                string "file:///mnt/mx500/mpd/music/BangDream/[Nemuri] BanG Dream! バンドリ！(2016-2020) [FLAC]/[2016-2019] Poppin'Party/[2019.01.30] Poppin'Party｜Poppin'on!/Poppin_on! [Disc 1]/09. 夢みるSunflower.flac"
         )
         dict entry(
            string "mpris:artUrl"
            variant                string "file:///mnt/mx500/mpd/music/BangDream/[Nemuri] BanG Dream! バンドリ！(2016-2020) [FLAC]/[2016-2019] Poppin'Party/[2019.01.30] Poppin'Party｜Poppin'on!/Poppin_on! [Disc 1]/cover.jpg"
         )
      ]
```

**Comment by ibotty** [comment]
This fixes my setup with mpd and mpDris2 (see issue #441).  It works beautifully!

**Comment by Riey** [comment]
@atheriel Now I can sure this will Fix #441 🚀

**Comment by pjeanjean** [comment]
This fixes my setup with Spotify, thanks for this!

**Comment by Riey** [comment]
Is there other remaining problems?

**Comment by ibotty** [comment]
Thank you all!

**Pull request merged**
