### PR TITLE
added notes about additional nixos packages

### PR DESCRIPTION
**Pull request by fkarg**

### CODE REVIEW

**Comment by atheriel** [comment]
Normally I would expect this to be part of the package documentation on NixOS -- is there a reason that won't be the case here?

**Comment by fkarg** [comment]
Not sure about that, since I'm pretty unfamiliar, but It took me some time to figure out, so I'd like to help others with similar needs

**Comment by ammgws** [comment]
Perhaps they could also be mentioned or added as optional dependencies to [the NixOS package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/i3/status-rust.nix)?

**Comment by fkarg** [comment]
Well I have no clue on how to do that, alas I just wanted to help people in a situation similar to mine, through the way I knew. I wanted to look into this at some point, but I do not have time for this currently, so this might take a while.

**Comment by atheriel** [comment]
I have filed an upstream bug, let's see how that goes.

**Comment by ammgws** [comment]
https://github.com/NixOS/nixpkgs/issues/79140 for reference

**Comment by ammgws** [comment]
Looks like this has been resolved upstream (the `sysfsutils` part anyway).

**Pull request closed without merging**
