### PR TITLE
Allow for reading theme information from standalone files

### PR DESCRIPTION
**Pull request by atheriel**
This PR introduces a new `theme.file` key to the TOML configuration, which makes it possible to use complete themes not provided by `i3status-rs` itself. We look in the following locations for this file:

- The actual file location, if it is a real path.
- `$XDG_CONFIG_HOME/i3status-rs/themes`; and
- `/usr/share/i3status-rs/themes`

The theme file must be "complete", e.g. contain all of the keys, for it to be serialized correctly. 

In the process, I did a lot of cleanup for deserialization of the `[theme]` section itself to make it clearer and more transparent; it should be much easier to add functionality there in the future.

As an aside: this could make it possible for us to extract the built-in themes and install them in, e.g. `/usr/share/i3status-rs/themes`.

### CODE REVIEW

**Comment by atheriel** [comment]
[Related comment](https://github.com/greshake/i3status-rust/issues/3#issuecomment-377714954) in #3.

**Comment by atheriel** [comment]
I've just realized that this breaks `theme = name`-style configurations, and can't be merged as-is.

**Comment by greshake** [comment]
What is your status on this?

**Comment by atheriel** [comment]
Still like the idea, have to fix the broken config issue. The custom deserialization code here is pretty hairy and  I wasn't able to find a solution at the time. I'll get back to it.

**Comment by PicoJr** [comment]
> I've just realized that this breaks `theme = name`-style configurations, and can't be merged as-is.

Hello, after cherry-picking this PR, I tried to fix the issue above.

I have duplicated `Config` struct into `LegacyConfig`.

```toml
# LegacyConfig
theme = "solarized-dark"
```

vs

```toml
# Config
[theme]
name = "solarized-dark"
```

can be deserialized into `LegacyConfig` struct using serde (as before).

I have implemented `From<LegacyConfig> for Config` that way `LegacyConfig` can be transformed into `Config` right away.

When loading config, we try deserialize it to `Config` first and if it fails we try to deserialize it to `LegacyConfig`:

```rust
// main.rs
    let config: Result<Config> = deserialize_file(config_path.to_str().unwrap());
    let config = config.or_else(|_| {
        let legacy_config: Result<LegacyConfig> = deserialize_file(config_path.to_str().unwrap());
        legacy_config.map(|legacy| legacy.into())
    })?;
```

see https://github.com/PicoJr/i3status-rust/commit/40fe25febaa192fb23748d8210b7726e706b05b3

What do you think?

**Comment by atheriel** [comment]
Oh, that's a clever solution. Yes, I think we could move forward with this, then.

**Comment by ammgws** [comment]
Closing in favour of #611

**Pull request closed without merging**
