### PR TITLE
[WAIT] Bump `uuid` crate to reduce dependencies

### PR DESCRIPTION
**Pull request by ammgws**
Merge this once the next release of `uuid` that contains [this](https://github.com/uuid-rs/uuid/pull/447) is out. (Make sure to update Cargo.* files first.)

Before (10): 
c2-chacha, cfg-if, getrandom, libc, ppv-lite86, rand, rand_chacha, rand_core, rand_hc, wasi

After (4):
 cfg-if, getrandom, libc, wasi

### CODE REVIEW

**Comment by PhilipConte** [comment]
the uuid crate version has since been bumped. It seems like this PR should be able to be closed.

**Comment by ammgws** [comment]
It's not in an actual release yet
https://github.com/uuid-rs/uuid

**Comment by ammgws** [comment]
Will rebase once https://github.com/uuid-rs/uuid/issues/475 has been resolved

**Comment by ammgws** [comment]
Closing in favour of #921

**Pull request closed without merging**
