### PR TITLE
Process requests for update only  once

### PR DESCRIPTION
**Pull request by rtxm**
A proposed fix for #310 and very probably #290.

### CODE REVIEW

**Comment by atheriel** [comment]
@greshake I'd like you to review this, since you are the authority on the scheduler.

**Comment by greshake** [comment]
Could you please elaborate on how this could be the cause of said issued?

Comments:
1. This commit ignores that asynchronously scheduled tasks can request a delayed update by passing an update time in the future
2. The async updates are only processed once already as far as I can tell; They don't get 'special treatment' so to say, instead they land in the same queue as the rest of the planned updates to allow for 'bundeling' of updates which occur at the same time

**Comment by greshake** [comment]
I agree that this should fix the issues we've had, but it is a 'dirty' solution in a way, for several reasons:

1. It ignores the ability of the update requests to contain a delay (arguably a feature we don't really need and don't use, so that is okay for now)
2. It leads to duplication. We now have two places where block updates are executed

Because I don't see any simpler solution right now, we should accept this. Going forward, these issues will be entirely resolved in the new architecture I'm planning...

@rtxm Thanks for investigating, the issue is now clear to me. Your solution is straight forward and should work :) Just to have it on record, here is my take on the bug:
Affected: Every block which schedules updates via the return parameter of the update function every time and also schedules async updates.
Example: Take a block which has a counter: It ticks every second and increments it by 1. The update function returns an interval of one second. When clicked, it schedules an update via the async pipeline to increment the value by an additional 1. 
When started, the block works as expected, incrementing the value every second. If clicked at, say 1.5s after start, the value is again incremented, but now the updater schedules and additional update for 2.5s (because the update function noted it wants to be called 1s later). The block now increments every half second.

**Comment by rtxm** [comment]
I'm aware the solution is not "clean" as I'd love it to be ;-) ; the intent was to spotlight the problem and start a discussion as didn't want to touch the architecture in anyway. 

The bug is exactly as you describe it, you explain it better than me.

I enjoy very much i3status-rust and I'm willing to help. Do not hesitate to open a discussion about the new architecture.

**Pull request merged**
