### PR TITLE
Add shell.nix for dev environment

### PR DESCRIPTION
**Pull request by cortices**
Take 3. Should be just the commit for this feature. sorry about all the extra emails you must be getting!

### CODE REVIEW

**Comment by ammgws** [comment]
I'm on Arch, but this feels out of place... Why does it need to be upstream?

**Comment by bim9262** [comment]
I'm also on arch, but you're right it does feel out of place... but I don't know much about how nix works

**Comment by bim9262** [comment]
Perhaps https://github.com/NixOS/nixpkgs would be more appropriate?

**Comment by cortices** [comment]
nixpkgs isn't really the right place, that's for packages (of which there already is one in home-manager instead).
shell.nix file is to set up the requisite development dependencies. It shouldn't require changes -- it just tells nixOS what is needed to build a rust project, without necessarily having a rust env already on the machine. if you don't want it in the project, you don't have to keep it.

**Comment by MaxVerevkin** [comment]
Any thoughts on this being in the wiki instead?

**Pull request closed without merging**
