### PR TITLE
Backligth Icons: Correct backlight order

### PR DESCRIPTION
**Pull request by alt-art**
In the old backligth icons the sun is 5% and the moon is 100%, i just replace the order to make sun 100% and moon 5%

### CODE REVIEW

**Comment by ammgws** [comment]
Just to be sure, does the `invert_icons` option help you?
See https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#options-1

Past issues: 
- #183
- #452
- #573
- #845
- #1081

**Comment by alt-art** [comment]
Was bad I didn't know I had an option for that, You know that having an option for this is kind of meaningless, I mean you know that everywhere the sun gets hot right?

**Comment by alt-art** [comment]
And by default it should be like I said, it only happens on awesome and awesome5

**Comment by alt-art** [comment]
You ended up making people believe they were wrong

**Comment by ammgws** [comment]
Let's keep it civil.

@GladOSkar Looking back at this, what do you reckon now? (I don't use this block daily)

**Comment by alt-art** [comment]
The fact that they have an option to invert is super cool but that won't change the fact that the order is wrong, sorry if it felt rude

**Comment by MaxVerevkin** [comment]
@alt-art Do you have colorful icons? Can you post a short GIF in with you change your backlight through all the values? I have monochrome font and it both `awesome` and `awesome5` work for me.

**Comment by GladOSkar** [comment]
Hi @alt-art - The reason these icons are the way they are is because they stem from a time when colored emoji weren't a thing on most systems. When using these icons with a monospaced font with a light text color on a dark background, it actually looks right that way.

Therefore, when color emoji started to become more prevalent, the option was introduced to allow those to look right as well while still maintaining backwards compatibility for existing setups. This is why just changing the icons is not an option - it would break the setups of everyone who uses light monochrome fonts on a dark background (which is actually still most people AFAIK).

**Comment by MaxVerevkin** [comment]
Btw, dark text on light background works too.

**Comment by GladOSkar** [comment]
Yeah in that case it's kinda ambiguous last time I checked it, it's really down to interpretation what side of the icons is "bright" and which is "dark" then

**Comment by alt-art** [comment]
Some icons are small, not all

**Comment by MaxVerevkin** [comment]
@alt-art
> Would it be possible to increase an icon without increasing the font?

Yes, you can try the following config option

```toml
icons_format = " <span size='x-large'>{icon}</span> "
```

For more info, refer to [pango docs](https://docs.gtk.org/Pango/pango_markup.html)

**Pull request closed without merging**
