### PR TITLE
Use `clap` macros for version info etc

### PR DESCRIPTION
**Pull request by ammgws**

### CODE REVIEW

**Comment by atheriel** [comment]
1. What's the advantage of these over the current environment variables?
2. Do you know why this includes `Cargo.lock` changes?

**Comment by ammgws** [comment]
1. Either is fine, just less boilerplate this way since clap abstracts it away for us.

2. It looks like the new merge friendly Cargo.lock V2 format. Seems like conversion that was merged the other day didn't actually end up converting the file. Sigh. 
I can remove it from this PR if necessary.

**Comment by atheriel** [comment]
Better to break out the lockfile changes into a separate commit, then.

**Comment by ammgws** [comment]
@greshake Done

**Comment by ammgws** [comment]
@atheriel Done

**Pull request merged**
