### PR TITLE
Use serde_json to get ip address instead of sed

### PR DESCRIPTION
**Pull request by ammgws**
This is possible as `ip` has a JSON output option.

TODO
- [ ] Check what our oldest supported system is

### CODE REVIEW

**Comment by ammgws** [comment]
Hmm, the `-json` flag might not be available on some older systems:
https://lwn.net/Articles/738897/

**Comment by flying7eleven** [comment]
Is there any commitment on compatibility with distributions? And if there is one, how many version / years should it be tested on? So far I didn't knew about a commitment and I would be interested so I could tests my own pull-request against it.

**Comment by ammgws** [comment]
I don't think there's an official commitment, but Ubuntu 18.04LTS users seem to pop up quite often in my experience so from 18.04 onwards might be a good reference point in general.

**Comment by flying7eleven** [comment]
Thanks @ammgws, I try to keep that in mind while testing :+1: For this pull request this would seem to be fine then I guess. Ubuntu 18.04 seems to ship with an compatible version (https://packages.ubuntu.com/bionic/iproute2).

**Comment by ammgws** [comment]
Thanks for that, when I checked last time it seemed like they were still on an older version.

**Comment by ammgws** [comment]
Hmm from a quick look I can't find any commits where something like that was fixed: https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/log/?qt=grep&q=json

Wonder how prevalent this is

**Comment by ammgws** [comment]
Aside from reverting this commit we could:

1. Fallback to parsing `ip` output using `sed` if cannot parse address from JSON. However this would mean the `ip` command would be run twice, plus having to keep around the previous code. Not really something I want to do.

2. Check the first member of the JSON array, and if it is empty then try the next member. This will lead to some code duplication but it would solve this issue.

3. Do nothing and file bug with upstream (or git bisect to see when this bug gets fixed)

**Comment by hlmtre** [comment]
Hey, thank you! I will have some time and energy this weekend and intend to tackle parsing the JSON, including the malformed one. I can submit a fix using the `ip -json`  version when complete.

**Pull request merged**
