### PR TITLE
Add "one-shot" mode and add some tests

### PR DESCRIPTION
**Pull request by ammgws**
As discussed in #555 

Also added a simple config to be tested with the compiled binary. It can be run locally as well using `cargo test`, and is tested by Travis CI as well.

### CODE REVIEW

**Comment by ammgws** [comment]
Looks like it's working well

**Comment by atheriel** [comment]
I'm not sure I'm a huge fan of running external commands in a test harness -- wouldn't a better alternative be to make `run()` possible from a test?

We could do this by hoisting config parsing (and profiling) into `main()` and then pass a `config: Config, one_shot: bool` to `run()`.

**Comment by ammgws** [comment]
The reason I thought of this in the first place was because a bug in the config parser (when attempting to switch to getopts) went unnoticed because the profiling args are only compiled for debug releases. I saw a comment from one of the Rust/Cargo maintainers mentioning testing this way which is why I opted for it.

Either way I'd be happy with something that can test both parts.

**Comment by ammgws** [comment]
Since this is just used for tests I will merge for now, and improvements can be made later.

**Pull request merged**
