### PR TITLE
Add dunst notification toggle

### PR DESCRIPTION
**Pull request by thomaspeklak**
This adds a bell icon that can turn on or off [Dunst](https://dunst-project.org/) notifications. It mirrors the functionality of the corresponding [bumblebee module](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/main/bumblebee_status/modules/contrib/dunst.py)

I don't know any Rust and probably did some stuff wrong. It compiles and works as I have been using it for some days now. Please feel free to point out stuff that I missed.

### CODE REVIEW

**Comment by ammgws** [comment]
As it is now I believe this would be better off as a custom/toggle block (see dicussion here: https://github.com/greshake/i3status-rust/issues/715#issuecomment-640951152).

Also, I don't see an update function so the block wouldn't update if dunst was paused via another method.

However if this PR could be rewritten to use DBus to control/monitor dunst then I think it would be a good addition as a native block. It looks like you can get and also set dunst's current state through dbus -  see the code for `is-paused` and `set-paused` in dunstctl: https://github.com/dunst-project/dunst/blob/fb2ffd425e2cfe42de0c633bcdf3a0203bfef90d/dunstctl#L67. You can probably monitor DBus for changes to that property as well, which means we can make the block update instantly if dunst was paused/unpaused by another method.

**Comment by thomaspeklak** [comment]
I have not

**Comment by thomaspeklak** [comment]
I have not seen the other ticket. If it makes more sense in your architectural concept to do this in another way, you can just decline the issue for now.

Otherwise I will look into dunstctl and figure out how to do the dbus stuff.

I am interested to take over dunst and dnf.

**Comment by ammgws** [comment]
What's dnf?

**Comment by thomaspeklak** [comment]
> What's dnf?
dnf ist the package manager for Fedora

**Comment by ammgws** [comment]
#851 should cover this if you are able to use the latest git version of dunst

**Pull request closed without merging**
