### PR TITLE
Fix rotating text widget width

### PR DESCRIPTION
**Pull request by ammgws**
Currently the minimum size of the block is hardcoded to 240 pixels for reasons unknown.
This leads to issues such as #223 with the music block.

Proposed changes:
- set `min_width` based on the user provided `width` value
- `min_width` should be set by characters (by passing a string) instead of by pixels

EDIT:
**1) Fixed the max_width setting for the widget**
Before (latest i3status-git, max_width set to 10 yet block size is large)
ezgif-3-bd71b56c94

After (this PR):
ezgif-3-367da31595

**2) Fixed the 'jitter' during scrolling:**
Before (latest i3status-git):
ezgif-3-78bdb17443

After (this PR):
ezgif-3-1cc0242860 1

### CODE REVIEW

**Comment by ammgws** [comment]
Fixing the 'jitter' during scrolling:

Before (latest i3status-git):
ezgif-3-78bdb17443

After (this PR):
ezgif-3-1cc0242860 1

**Comment by ammgws** [comment]
Updated first post with visual of fixes.

**Comment by atheriel** [comment]
This looks good to me, but I'm not a consumer of the music block and I know it's @greshake's baby. We'll wait a bit to see if he has anything to say.

**Comment by greshake** [comment]
All good. To quote the i3bar protocol docs: 

> The value can also be a string. In this case, the width of the text given by min_width determines the minimum width of the block. This is useful when you want to set a sensible minimum width regardless of which font you are using, and at what particular size. 

Nice, I didn't know!

**Pull request merged**
