### PR TITLE
Allow custom blocks with JSON not to set an icon

### LINKED ISSUE #1156: Error with custom block json with no icon
```
Internal error in context 'get_icon()': icon '' not found: please check your icon file or open a new issue on GitHub if you use a precompiled icons.
```

icons = "awesome"

The json I emitted was:
```
{"state":"Critical", "text":" Reboot Required"}
```

### PR DESCRIPTION
**Pull request by GladOSkar**
Resolves #1156

Regressed in #1135, feedback welcome

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
One issue: If the custom script is dynamic, then there is no way to disable the icon once it is already shown.

**Comment by GladOSkar** [comment]
Ah yes i see. I don't think there's a way to explicity unset an icon programmatically yet, right?

**Comment by MaxVerevkin** [comment]
Probably have to add a new function to the `TextWidget`.

**Comment by GladOSkar** [comment]
Okay this should work now. Not sure if this is the proper way to do it, maybe this could be done easier during deserialization of the json but i have no idea how

**Comment by ammgws** [comment]
Thanks!

**Pull request merged**
