### PR TITLE
net: implement ip&ipv6

### LINKED ISSUE #1069: net block: investigate using netlink/nl80211 instead of shelling out
As long as dependencies don't get too out of hand, this would be a step towards simplifying the block and for us to truly be "pure Rust" (or closer anyway by using C bindings).

- [ ] ip
- [ ] ipv6
- [x] bitrate (https://github.com/greshake/i3status-rust/commit/99062389e24e9026b25874514ace70c60f03634c)
- [x] ssid (completed with #1142)
- [x] frequency (completed with #1142)
- [x] signal strength (completed with #1142)

### LINKED ISSUE #1515: v0.30: reimplement ip, ipv6 and bitrate (for wired connections) placeholders for net block
I think ip/ipv6 can be done via netlink, not sure about bitrate though.

### LINKED ISSUE #1595: `net` incorrect default interface
I believe I discovered a bug after installing docker my net block no longer rendered.

```
$ ip route list
default via 192.168.1.1 dev wlp166s0 proto dhcp src 192.168.1.50 metric 600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.1.0/24 dev wlp166s0 proto kernel scope link src 192.168.1.50 metric 600
```

`fn default_interface()` in `netlink.rs` returns `Some("docker0")`. I expected it would return `Some("wlp166s0")` as it is the interface of my _default_ route. 

Reading the source it seems to me `default_interface()` returns whatever netlink returned as the ~~"first"~~ "last"? interface. I can't tell if there is any guarantee this should be the default interface. Not sure if this is intended but it seems like odd behavior. 

Maybe this is related to #1515? #1515 is help wanted, I could look more into this.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
fixes #1515
fixes #1595
fixes #1069
notfixes #587

Needs testing.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
> Needs testing.

VPNs in particular (their presence, their default-ness, their up/down state)

**Comment by Alextopher** [comment]
Attempting to do some more detailed testing. 

Works are expected when there is a single default route:
```
$ ip route
default via 192.168.1.1 dev wlp166s0 proto dhcp src 192.168.1.50 metric 600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.1.0/24 dev wlp166s0 proto kernel scope link src 192.168.1.50 metric 600
```

However, when there are two default routes 
```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp0s20f0u4c4i2
default         _gateway        0.0.0.0         UG    600    0        0 wlp166s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.10.0     0.0.0.0         255.255.255.240 U     100    0        0 enp0s20f0u4c4i2
192.168.1.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp166s0
```

the default interfaces function returns the last default route while the kernel seems to prefer using the first.

**Comment by Alextopher** [comment]
Using private internet access VPN (`tun0` interface name) works for me :+1:

**Comment by MaxVerevkin** [comment]
> the default interfaces function returns the last default route while the kernel seems to prefer using the first.

Thanks, fixed.

**Comment by MaxVerevkin** [comment]
> Also was bitrate for wired connections available via netlink?

via netlink but not rtnetlink... see https://github.com/greshake/i3status-rust/issues/1515#issuecomment-1213807759

**Comment by Alextopher** [comment]
I wonder if this creates a minimum supported kernel version

**Comment by ammgws** [comment]
Are you talking about the SSID issue?

**Comment by ammgws** [comment]
I think this should be OK for now

**Pull request merged**
